### ISSUE TITLE
Single word timestamps

### ISSUE THREAD

**Issue by RoryMcHughh** [sandrohanea/whisper.net#101]
Is there a way to get single word timestamps instead of sentences? I tried SplitOnWord() but it isnt working.

**Comment by sandrohanea** [comment]
Each Word of the english vocabulary is a token in the output of whisper.
In order to get these timestamps for each token, you can use: https://github.com/sandrohanea/whisper.net/blob/b927e36b9c5b402325abd519f0c23e4e0505227d/Whisper.net/WhisperProcessorBuilder.cs#L177
