### ISSUE TITLE
whisper_init_from_file_no_state on windows server 2012~~~

### ISSUE THREAD

**Issue by ijustkeepmoving** [sandrohanea/whisper.net#108]
<PackageReference Include="Whisper.net" Version="1.4.7" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.4.7" />
    <PackageReference Include="Whisper.net.Runtime.CoreML" Version="1.4.7" />

logs:
hisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4
whisper_model_load: mem required  = 1899.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     = 1462.58 MB
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External
component has thrown an exception.
Repeat 2 times:
--------------------------------
   at Whisper.net.Native.NativeMethods.whisper_init_from_file_no_state(System.St
ring)
--------------------------------
   at Whisper.net.Internals.ModelLoader.WhisperProcessorModelFileLoader.LoadNati
veContext()
   at Whisper.net.WhisperFactory..ctor(Whisper.net.Internals.ModelLoader.IWhispe
rProcessorModelLoader, Boolean, System.String, Boolean)
   at WhisperLib.WhisperHelper+<Transcribe>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[WhisperLib.W
hisperHelper+<Transcribe>d__1, WhisperNETAPI, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null]](<Transcribe>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon,
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d
7bea7798e]].Start[[WhisperLib.WhisperHelper+<Transcribe>d__1, WhisperNETAPI, Ver
sion=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Transcribe>d__1 ByRef)
   at WhisperLib.WhisperHelper.Transcribe(Options)
   at WhisperNETAPI.Service.MusicLrcService+<<StartAsync>b__6_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[WhisperNETAP
I.Service.MusicLrcService+<<StartAsync>b__6_0>d, WhisperNETAPI, Version=1.0.0.0,
 Culture=neutral, PublicKeyToken=null]](<<StartAsync>b__6_0>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[WhisperNETAP
I.Service.MusicLrcService+<<StartAsync>b__6_0>d, WhisperNETAPI, Version=1.0.0.0,
 Culture=neutral, PublicKeyToken=null]](<<StartAsync>b__6_0>d ByRef)
   at WhisperNETAPI.Service.MusicLrcService.<StartAsync>b__6_0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Ver
sion=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Thr
eading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallba
ck, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.
Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

![image](https://github.com/sandrohanea/whisper.net/assets/12046942/11e1bf27-cbcc-488d-ab68-2bbaf11880ae)

**Comment by ijustkeepmoving** [comment]
![image](https://github.com/sandrohanea/whisper.net/assets/12046942/106f64a8-10ea-40fe-8a70-237612e3bff7)

**Comment by ijustkeepmoving** [comment]
sorrry~i have removed the CoreML DLL

but the error still exists .

What makes me strange is the application can run correctly on another windows server 2012 




info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\tc1shiny\AppData\Local\ASP.NET\
DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'WhisperNETAPI.Controllers.TaskController.Submit (Whisp
erNETAPI)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Submit", controller = "Task"}. Executing con
troller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore
.Mvc.ActionResult`1[WhisperNETAPI.APIResponse]] Submit(Int32) on controller Whis
perNETAPI.Controllers.TaskController (WhisperNETAPI).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'WhisperNETAPI.APIResponse'.

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action WhisperNETAPI.Controllers.TaskController.Submit (WhisperNE
TAPI) in 1136.5749ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'WhisperNETAPI.Controllers.TaskController.Submit (Whispe
rNETAPI)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/task?musicid=7483574 -
 - - 200 - application/json;+charset=utf-8 1324.1593ms
whisper_init_from_file_no_state: loading model from 'ggml-m
edium.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4
whisper_model_load: mem required  = 1899.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     = 1462.58 MB
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External
component has thrown an exception.
Repeat 2 times:
--------------------------------
   at Whisper.net.Native.NativeMethods.whisper_init_from_file_no_state(System.St
ring)
--------------------------------
   at Whisper.net.Internals.ModelLoader.WhisperProcessorModelFileLoader.LoadNati
veContext()
   at Whisper.net.WhisperFactory..ctor(Whisper.net.Internals.ModelLoader.IWhispe
rProcessorModelLoader, Boolean, System.String, Boolean)
   at WhisperLib.WhisperHelper+<Transcribe>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[WhisperLib.W
hisperHelper+<Transcribe>d__1, WhisperNETAPI, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null]](<Transcribe>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon,
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d
7bea7798e]].Start[[WhisperLib.WhisperHelper+<Transcribe>d__1, WhisperNETAPI, Ver
sion=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Transcribe>d__1 ByRef)
   at WhisperLib.WhisperHelper.Transcribe(Options)
   at WhisperNETAPI.Service.MusicLrcService+<<StartAsync>b__8_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.Service.
MusicLrcService+<<StartAsync>b__8_0>d, WhisperNETAPI, Version=1.0.0.0, Culture=n
eutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionCo
ntext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.Service.
MusicLrcService+<<StartAsync>b__8_0>d, WhisperNETAPI, Version=1.0.0.0, Culture=n
eutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.Service.
MusicLrcService+<<StartAsync>b__8_0>d, WhisperNETAPI, Version=1.0.0.0, Culture=n
eutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Ru
ntime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Ver
sion=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(Sy
stem.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon,
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d
7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>,
 System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon,
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d
7bea7798e]].SetResult(System.__Canon)
   at WhisperNETAPI.MusicDownloader+<Down>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
 PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.MusicDownloader+<Down>d__1, Whi
sperNETAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionCon
textCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionCo
ntext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
 PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.MusicDownloader+<Down>d__1, Whi
sperNETAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(Sys
tem.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
 PublicKeyToken=7cec85d7bea7798e],[WhisperNETAPI.MusicDownloader+<Down>d__1, Whi
sperNETAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Ru
ntime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, Syst
em.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea
7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading
.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
 PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.
Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskRe
sult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at System.Net.Http.HttpConnection+ContentLengthReadStream+<CompleteCopyToAsyn
c>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+ContentLengthReadStream+<CompleteCopyToAsync>d__5, System.Net.Http, Ver
sion=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContex
tCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionCo
ntext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+ContentLengthReadStream+<CompleteCopyToAsync>d__5, System.Net.Http, Ver
sion=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System
.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+ContentLengthReadStream+<CompleteCopyToAsync>d__5, System.Net.Http, Ver
sion=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Ru
ntime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, Syst
em.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea
7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading
.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
 PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.
Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskRe
sult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at System.Net.Http.HttpConnection+<CopyToContentLengthAsync>d__112.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+<CopyToContentLengthAsync>d__112, System.Net.Http, Version=6.0.0.0, Cul
ture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(System.
Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionCo
ntext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+<CopyToContentLengthAsync>d__112, System.Net.Http, Version=6.0.0.0, Cul
ture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System.Threading.Thread
)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachine
Box`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.
0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpCo
nnection+<CopyToContentLengthAsync>d__112, System.Net.Http, Version=6.0.0.0, Cul
ture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.ThreadPool+<>c.<.cctor>b__87_0(System.Object)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[[System.In
t64, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7c
ec85d7bea7798e]].SignalCompletion()
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.Execu
teInternal()
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.Syste
m.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by sandrohanea** [comment]
Sounds like the ggml model which is loaded is not corrupted or have some issues.
How you downloaded that ggml-medium.bin?

Also, can you, please, try to just load the library using that model like this: `    using var whisperFactory = WhisperFactory.FromPath("ggml-medium.bin");`?

Can you, please, also confirm the size of that file?

**Comment by brooklet** [comment]
I had the same problem. 

When loading ggml-medium.bin using 32 bit whisper.dll, The exception "Whisper.net.WhisperModelLoadException: "Failed to load the whisper model."" is thrown.  

This exception is not thrown when loading ggml-small.bin or smaller models.

**Comment by sandrohanea** [comment]
Is the issue still reproducing with Whisper.net 1.5.0?

There are a lot of ggml fixes in the underlying library (whisper.cpp) included in this release.

**Comment by sandrohanea** [comment]
Will close due to inactivity. Version 1.7.1 is the latest one that now supports multiple runtimes referenced in the same project and should work as expected. If that's not the case, feel free to open a new ticket.
