### ISSUE TITLE
Illegal Instruction when AVX is not available on the Host

### ISSUE THREAD

**Issue by piotr-k-k** [sandrohanea/whisper.net#110]
Hi, unfortunatelly I get unhandled exception trying run Whisper.net.Demo and I can't deal with it.
Unhandled exception at 0x00007FFB6C6B3441 (whisper.dll) in Whisper.net.Demo.exe: 0xC000001D: Illegal Instruction.
at line
NativeMethods.whisper_full_with_state(currentWhisperContext, state, whisperParams, (IntPtr)pData, samples.Length);
VS2022, .NET 7, Whisper 1.4.7
Any suggestions?
Thanks

**Comment by sandrohanea** [comment]
Hello @piotr-k-k ,
Do you have any changes to Whisper.net.Demo?

Are you using some specific wav file that you can share in order to reproduce the issue?


Also, can you, please, try some examples  from the "Examples" folder?
e.g. https://github.com/sandrohanea/whisper.net/tree/main/examples/Simple

**Comment by piotr-k-k** [comment]
Hello @sandrohanea, thank you for reply, no I didn't change anything and I used default kennedy.wav. I tested example Simple as well as my own test application, all with the same result.

**Comment by sandrohanea** [comment]
I still couldn't manage to reproduce the error. Can you, please, clarify the OS version and architecture(e.g. x64, arm64, x86) that you're using?

**Comment by piotr-k-k** [comment]
I used Windows 10 x64, today later or tomorrow maybe I will try other system and hardware.

**Comment by sandrohanea** [comment]
that is one of the systems that I'm using, and can confirm that it should work (just tested it). 
Can you maybe try to re-install https://aka.ms/vs/17/release/vc_redist.x64.exe
Maybe for some reason you have some corrupted vc redistributable?

**Comment by sandrohanea** [comment]
Another possible issue might be similar with: https://stackoverflow.com/questions/59584105/illegal-instruction-from-vs-c-on-windows

Which CPU are you using?

**Comment by piotr-k-k** [comment]
Now I don't know what exactly CPU I use, will check tomorrow. Thanks for tips, tomorrow I will continue deal with it.

**Comment by sandrohanea** [comment]
Hey all,
Forgot to update here, but version `1.7.1` was released for ~1 week and it contains the support for the NoAvx package.
You can either reference it individually or combine it with any other runtime (see https://github.com/sandrohanea/whisper.net?tab=readme-ov-file#multiple-runtimes-support )

If the AVX is not available on the host, Whisper.net.Runtime CPU version with AVX requirement won't be loaded anymore, so if you don't have a runtime for your host `System.IO.FileNotFoundException: Native Library not found in default paths.` will be thrown and not the Illegal Instruction exception.
