### ISSUE TITLE
Adding Distil-Whisper - distilled version of Whisper that is 6 times faster, 49% smaller 

### ISSUE THREAD

**Issue by strich** [sandrohanea/whisper.net#126]
Per the [HN ](https://news.ycombinator.com/item?id=38093353) link, it would be great to get Distil-Whisper as an option in this repo!

**Comment by sandrohanea** [comment]
Coming soon with 1.5.0
https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.0

**Comment by sandrohanea** [comment]
Distil whisper models are supported now, follow: https://github.com/ggerganov/whisper.cpp/tree/master/models#distilled-models to convert them to ggml and use them with whisper.net :)
