### ISSUE TITLE
Is there a way to suppress Console logging?

### ISSUE THREAD

**Issue by danroot** [sandrohanea/whisper.net#129]
I have a working example of transcoding mic input in real time, but see lots of whisper logging in the console that I would rather not see, like this:
whisper_init_state: kv self size  =    5.25 MB
whisper_init_state: kv cross size =   17.58 MB
whisper_init_state: loading Core ML model from 'ggml-base-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: Core ML model loaded
Is there some way to suppress this logging?

**Comment by sandrohanea** [comment]
Those logs are written by whisper.cpp library: https://github.com/ggerganov/whisper.cpp and currently there is no way of suppressing them.

I recommend you opening an issue there and if some config / option is added, will be added to this library as well.

**Comment by danroot** [comment]
Opened this issue: https://github.com/ggerganov/whisper.cpp/issues/1448 My pinvoke-fu is pretty weak, but I'm thinking something like whisper_set_log_callback(nil), or if there is some way to set the callback to a .NET method, we could intercept whisper.cpp output to parse & debug, but not show it unless we wanted.

**Comment by sandrohanea** [comment]
Logging is now suppresed by default, you can register some log handler to the [LogProvider](https://github.com/sandrohanea/whisper.net/blob/1.5.0/Whisper.net/Logger/LogProvider.cs) if you want to show that logs or use them in your app.

**Comment by contractorwolf** [comment]
is that true? I just downloaded it today and I get a ton of logs that I came looking to stop
