### ISSUE TITLE
1.5.0 release of Windows x64 cuBLAS runtime does not work

### ISSUE THREAD

**Issue by KanaHayama** [sandrohanea/whisper.net#142]
Hello, I upgraded my whisper.net packages from 1.4.7 to 1.5.0. I found that the CPU runtime is working, but the cuBLAS runtime does not produce results.
Are there other migration operations that I am missing? Thank you.

**Comment by sandrohanea** [comment]
Hello @KanaHayama ,
Can you, please confirm if you have installed Cuda 12.1?

Whisper.net 1.4.7 was built using Cuda 11, but starting with 1.5.0, the build was done using github actions and cuda 12.1 was used:
https://github.com/sandrohanea/whisper.net/blob/main/.github/workflows/windows-native-build.yml#L70

**Comment by KanaHayama** [comment]
I checked my CUDA_PATH, and it is pointing to CUDA 12.2.
My setting works with 1.4.7, but does not work with 1.5.0.

**Comment by KanaHayama** [comment]
Besides that, my PATH contains CUDA 12.2, 11.6 and 11.8. I did not notice that I have multiple CUDA listed in PATH, but I think this should be fine because 12.2 is in front of all others.
![image](https://github.com/sandrohanea/whisper.net/assets/15655296/6f7aedb7-d3e4-4be7-a2b9-2e6a64f887a0)

**Comment by shuaidaipeng** [comment]
使用CUDA\v12.3可以吗？ 目前它使用的还是cpu

**Comment by KanaHayama** [comment]
I installed and tested CUDA 12.3. The problem is the same. @shuaidaipeng

**Comment by shuaidaipeng** [comment]
> I installed and tested CUDA 12.3. The problem is the same. @shuaidaipeng
> 
> 
> 我安装并测试了CUDA 12.3。问题是一样的。@帅呆蓬

我研究了一下下它这个是根据自己的cuda版本编译出来的工具，所以对应其他版本的cuda需要自己去cmake 去编译

**Comment by MarkHXB** [comment]
Same here, Whisper.net uses my CPU instead the GPU. I've installed CUDA 12.4 and the following packages I use in my project:
Whisper.net Version="1.5.0"
Whisper.net.Runtime Version="1.5.0"
Whisper.net.Runtime.Cublas Version="1.5.0"

**Comment by foenix66** [comment]
Whisper.net.Runtime.Cublas下面的是编译以后的cuda版本whisper.dll，将他替换exe的runtime下的win-x64版本dll，启动cuda版本的Whisper.net.

**Comment by abbotadmin** [comment]
Anyone been able to fix this?

**Comment by abbotadmin** [comment]
I figured this out: Make sure you don't also have the `Whisper.net.Runtime` package. You must only have the  `Whisper.net.Runtime.Cublas` package, AND you must clean/rebuild your solution to force the correct dll into the built project.

**Comment by sandrohanea** [comment]
Hello all,
Starting with 1.7.0 you can now define multiple Runtimes in the same project and the "best" one will be automatically picked. Indeed, previous to this version, you couldn't have both Cuda and CPU runtime on the same project.
