### ISSUE TITLE
Not directly supporting MP3 format？

### ISSUE THREAD

**Issue by lmxin123** [sandrohanea/whisper.net#156]
Does it support recording in WAV format by default? Whisper itself supports all recording formats, why doesn't Whisper.net support all recording formats? Otherwise, we need to convert the format separately

**Comment by sandrohanea** [comment]
No other format than wave is supported natively by whisper. 

The python version (OpenAI) of the whisper is just using ffmpeg to decode other formats, but we don't want to add a hard-dependency on ffmpeg as in dotnet, most of the people might want to use NAudio. 

Also discussed in https://github.com/sandrohanea/whisper.net/issues/27

**Comment by lmxin123** [comment]
However, NAudio does not support Linux as it integrates too many Windows related APIs
