### ISSUE TITLE
Can we add speaker separation function

### ISSUE THREAD

**Issue by lmxin123** [sandrohanea/whisper.net#159]
For example, in a multiplayer meeting, distinguish the content of each speaker. Then output speaker1,2,3,4,5,6
@sandrohanea

**Comment by sandrohanea** [comment]
This is a diarization based on multiple wave streams (assuming each speaker will be on a different stream): https://github.com/sandrohanea/whisper.net/tree/main/examples/Diarization

However, if the speakers are not separated to different streams, you'll need to rely only on: https://github.com/sandrohanea/whisper.net/issues/161

Either use that experimental tiny diarize (which tells you when speaker is changing as a different token) or pre-separate the audio using another tool and use whisper.net only for speech to text => and not diarization.
