### ISSUE TITLE
Webspher.net often produces hallucinations

### ISSUE THREAD

**Issue by lmxin123** [sandrohanea/whisper.net#162]
How to solve the problem of hallucinations caused by using wispher.net? The model I am using is large-v3. Converting the same file multiple times can also cause hallucinations.

**Comment by sandrohanea** [comment]
This is a normal limitation of Whisper model, inherited in Whisper.cpp and Whisper.net. However, you can try to fine-tune the settings for your use-cases (check Temperature for example) https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/WhisperProcessorBuilder.cs#L333C3-L346C6

**Comment by lmxin123** [comment]
I adjusted the temperature to 0, but it had no effect and I still frequently experienced hallucinations. Whether using large v2 or large v3, it's the same
