### ISSUE TITLE
Can support Distil-Whisper model?

### ISSUE THREAD

**Issue by lmxin123** [sandrohanea/whisper.net#164]
Can support Distil-Whisper model?
I heard that the distillation model has a small scale, very high performance, very fast, and high recognition quality

**Comment by sandrohanea** [comment]
Hello @lmxin123 ,
Yes, distil models should be supported as described here: https://github.com/sandrohanea/whisper.net/issues/126

**Comment by dfengpo** [comment]
thank you，i try it later
hope you can update to 1.6，thanks
