### ISSUE TITLE
After running for a period of time, repeatedly output the same sentence

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#167]
I use model large-v3
When After running for a period of time, repeatedly output the same sentence like this:
00:00:00->00:00:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:00:29->00:00:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:00:59->00:01:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:01:29->00:01:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:01:59->00:02:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:02:29->00:02:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:02:59->00:03:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:03:29->00:03:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:03:59->00:04:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:04:29->00:04:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:04:59->00:05:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:05:29->00:05:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:05:59->00:06:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:06:29->00:06:59：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
00:06:59->00:07:29：请不吝点赞 订阅 转发 打赏支持明镜与点点栏目

Are there any parameters that can be set？

**Comment by lmxin123** [comment]
@sandrohanea

**Comment by sandrohanea** [comment]
Probably https://github.com/sandrohanea/whisper.net/issues/171 will help, also increasing temperature might help. However, this is an inference topic controlled by the underlying [whisper.cpp](https://github.com/ggerganov/whisper.cpp/tree/master) library.
