### ISSUE TITLE
How to improve recognition speed on CPU or increase concurrency

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#168]
How to improve recognition speed on CPU or increase concurrency？

Whether it's Model Large2 or Model Large3, recognition is very slow. I run it on the CPU, which has 16 cores

My CPU usage is only 12% and memory usage is only 18% in the entire running state. May I ask if there is a way to increase speed

**Comment by sandrohanea** [comment]
It will use multiple threads, but the maximum concurrency is the one that the underlying library will use (for both encoder and decoders). They are doing performance improvements all the time so you might check v1.7.0 for updated version. However, there is nothing we can do in this wrapper to improve the efficiency of CPU inference.
