### ISSUE TITLE
Where is "-mc 0" parameter

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#171]
I saw here discussing that the - mc 0 parameter can solve the problem of hallucinatory repeated output. Can Whisper.net support setting this parameter?

[https://github.com/ggerganov/whisper.cpp/issues/1244#issuecomment-1705391274](url)

#-mc 0 is equivalent to "condition_on_previous_text". It will remove "forever looping" output and also workaround other problems like counting up forever or lowercase forever. At the same time it will sometimes cause reduced transcribe quality.

-mc N,     --max-context N     [-1     ] maximum number of text context tokens to store
[https://github.com/search?q=repo%3Aggerganov%2Fwhisper.cpp%20-mc%200&type=code](url)

Can Whisper.net support this parameter？I urgently need this parameter to solve the problem of hallucinatory repetitive output

**Comment by sandrohanea** [comment]
Here it is: https://github.com/sandrohanea/whisper.net/blob/fc1282f9a92f03e854a66c65b39ef2c9dfdc23e4/Whisper.net/WhisperProcessorBuilder.cs#L44C36-L44C57
