### ISSUE TITLE
Is it possible to limit the vocabulary?

### ISSUE THREAD

**Issue by adscott1982** [sandrohanea/whisper.net#173]
My use case is very specific - and only needs to listen for an activation word, and maybe 12 or 13 different commands.

To improve the performance I would like to limit the vocabulary (or tokens?) to just those words.

I read the ticket here and it seems it is possible:

https://github.com/openai/whisper/discussions/843

I am wondering if it is possible to do it from your .NET wrapper?

I won't be able to install python on the target machine, so would like to implement this so I can just drop in the required DLLs and run the executable to start listening for the commands from the user.

![image](https://github.com/sandrohanea/whisper.net/assets/12865303/916e5d46-f92b-412a-8f97-833c2c2bbe23)

**Comment by adscott1982** [comment]
I see the 'tokenize' function is available on **NativeMethods.cs**

https://github.com/sandrohanea/whisper.net/blob/28839bf0aa80c723a68d2876f9adbb0a0f21d0d2/Whisper.net/Internals/Native/NativeMethods.cs#L70C1-L71C1

![image](https://github.com/sandrohanea/whisper.net/assets/12865303/d7c68fb2-4692-433a-91d8-fa728228adc2)

Is there a way to 'get_tokenizer' as in the python example through the C# wrapper?

**Comment by adscott1982** [comment]
Wait - I just saw you have a custom GPT - I will give it a shot.

**Comment by sandrohanea** [comment]
Hello @adscott1982 

Indeed, the custom GPT was not able to do it. You can now (starting with 1.7.0) do it using: `WithSuppressRegex` https://github.com/sandrohanea/whisper.net/blob/fc1282f9a92f03e854a66c65b39ef2c9dfdc23e4/Whisper.net/WhisperProcessorBuilder.cs#L276

Here is the code in the whisper.cpp library for it: https://github.com/ggerganov/whisper.cpp/blob/ebca09a3d1033417b0c630bbbe607b0f185b1488/src/whisper.cpp#L4967C10-L4967C48

There is no way to have a custom logitsfilter for now but this should help to limit the vocabulary.

**Comment by adscott1982** [comment]
Thank you very much!
