### ISSUE TITLE
Automatic Runtime Selection

### ISSUE THREAD

**Issue by srs-adamr** [sandrohanea/whisper.net#181]
Was considering contributing a Source Generation library to automatically select Whisper.net.Runtime.Cublas/Whisper.net.Runtime.Clblast based on the available hardware / os. 

Are there any limitations anyone is aware of that would pose a challenge in doing this?

**Comment by Lyrcaxis** [comment]
The developers can do this 'automatic' selection 'manually' by including multiple DLLs in the build and specifying libraryPath.
As for fully automatically and built-in it's @sandrohanea's call on whether it should or shouldn't happen.
