### ISSUE TITLE
Whisper.net x LLamaSharp example

### ISSUE THREAD

**Issue by Lyrcaxis** [sandrohanea/whisper.net#185]
I made a PR with usage examples for Whisper.net as a server and in combination with LlamaSharp: https://github.com/SciSharp/LLamaSharp/pull/656
I thought people may benefit as I think it's better than the current demo of Whisper.net.

Oh, and.. thanks for the C# library, great job @sandrohanea and contributors!

**Comment by sandrohanea** [comment]
That's great!

Thanks for the contributions and for making it more popular! :)
