### ISSUE TITLE
If this parameter is supported--condition_on_previous_text False

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#188]
I often encounter problems with hallucinations, and as this discussion suggests, configuring this parameter can solve the problem of hallucinations.

[https://github.com/openai/whisper/pull/1253](url)

May I ask if wishper.net can support this parameter?
Or is there a solution on the official website to solve hallucinations? I am using the V3 model

**Comment by sandrohanea** [comment]
Nom that parameter is not supported by whisper.cpp: https://github.com/ggerganov/whisper.cpp/issues/1244#issuecomment-1705391274

But `-mc 0` should be there which is equivalent based on those comments. 

For whisper.net, the equivalent of `-mc 0` is: 
```
processorBuilder
.WithMaxTextTokens(0)
```

See: https://github.com/sandrohanea/whisper.net/blob/fc1282f9a92f03e854a66c65b39ef2c9dfdc23e4/Whisper.net/WhisperProcessorBuilder.cs#L44C36-L44C57
