### ISSUE TITLE
Why is the performance so low

### ISSUE THREAD

**Issue by Chris20210426** [sandrohanea/whisper.net#194]
I ran a sample program using this library based on Windows ARM. When processing a 13 minute source audio, it takes 11 minutes to complete, while the whisper official command-line program only takes less than two minutes. Is there any optimization method available? By the way, the test is based on the same ggml model.

**Comment by sandrohanea** [comment]
If you have access to GPU/NPU you can try to use a different runtime. See https://github.com/sandrohanea/whisper.net/tree/fc1282f9a92f03e854a66c65b39ef2c9dfdc23e4?tab=readme-ov-file#gpu-support
 Also make sure you install latest version( 1.7.0) as the underlying library (whisper.cpp) had a lot of performance improvements.

**Comment by sandrohanea** [comment]
Will close this due to inactivity.
In general, using a faster runtime will help.However, if the host is only supporting NoAvx runtime, that is expected to be slower.
