### ISSUE TITLE
The lib hangs if processing concurrently

### ISSUE THREAD

**Issue by atmoraes1** [sandrohanea/whisper.net#195]
When spawning multiple transcriptions at the same time, the lib hangs and keeps using CPU forever. 

It seems something is not thread safe but I'm not sure. What could be causing that?

**Comment by sandrohanea** [comment]
Probably you reused some WhisperProcessor across multiple threads.

You should be able to run parallel transcoding without any locking and loading the model only once, if creating one [WhisperFactory](https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/WhisperFactory.cs) that you're going to reuse, but for each thread / task, use a different [WhisperProcessor](https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/WhisperProcessor.cs)

**Comment by atmoraes1** [comment]
That's exactly what I'm doing. The factory is static and each audio input creates a new processor.

**Comment by sandrohanea** [comment]
Please, check latest version (1.7.0) and the example https://github.com/sandrohanea/whisper.net/tree/main/examples/ParallelExecution

This is the result (where the output is interleaved and the lib is not hanging):
![image](https://github.com/user-attachments/assets/d23a26e0-38f7-4916-be4d-6bb6bc434501)
