### ISSUE TITLE
Failed to load native whisper library. Error: Unknown error

### ISSUE THREAD

**Issue by parabola949** [sandrohanea/whisper.net#196]
I built a small, simple test application on my windows machine (VS 2022, Win11)
Worked great, so I did `dotnet build .\WhisperNetTesting\WhisperNetTesting.csproj --runtime linux-x64`, deployed to a linux machine (CentOS), and I'm getting the following now:
```Processing tests using model ggml-large-v3-q5_0.bin
Downloading Model ggml-large-v3-q5_0.bin
Unhandled exception. System.Exception: Failed to load native whisper library. Error: Unknown error
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit, String libraryPath, Boolean bypassLoading)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization, String libraryPath, Boolean bypassLoading, Boolean useGpu)
   at Program.<Main>$(String[] args) in N:\source\Various Testing\WhisperNetTesting\Program.cs:line 45
   at Program.<Main>(String[] args)
Aborted (core dumped)
```

I'm really just trying to see if this is a viable solution for something I'm working on, and so far this looks like it would be a great solution for my team, but I'm having trouble getting this small sample to run.  Am I doing something silly, or am I just missing something.  I also tried a regular build (without declaring runtime), same error.
Using .NET 6.0

**Comment by jkkgrk** [comment]
I encountered a similar error message.(with Runtime.Cublas) After checking, I found that the problem was due to improperly configured CUDA environment variables. If you have a similar situation, you might want to check your environment variables.

**Comment by sandrohanea** [comment]
It should be possible to build on Windows and deploy in the linux machine (as the native binaries are built using ubuntu 20) 

Not sure which version of `libc.so` are you using on the centos machine, but it should be minimum the one that is on ubuntu 20. 

Worst case, if you cannot upgrade that library on the CentOS machine, you can build the runtime yourself, this is the github actions that builds it for linux CPU + cuda linux: https://github.com/sandrohanea/whisper.net/blob/main/.github/workflows/linux-native-build.yml
