### ISSUE TITLE
my gpu not work

### ISSUE THREAD

**Issue by billqu01** [sandrohanea/whisper.net#198]
I have installed Whisper.net.Runtime.Clblast 
My code is below:
using var whisperFactory = WhisperFactory.FromPath("ggml-small.bin", useGpu: true);
But cpu is worked, and gpu not.
How to soluv?
Thanks.

**Comment by abbotadmin** [comment]
I figured this out: Make sure you don't also have the `Whisper.net.Runtime` package. You must only have the  `Whisper.net.Runtime.Cublas` package, AND you must clean/rebuild your solution to force the correct dll into the built project.
