### ISSUE TITLE
WithDuration() is not working?

### ISSUE THREAD

**Issue by LainNya** [sandrohanea/whisper.net#20]
Hi!
I want to transcribe audio for only one duration. When I use both WithOffset() and WithDuration(), Whisper often outputs text that exceeds the duration setting length, is it my problem?

**Comment by sandrohanea** [comment]
Hello @LainNya,
I checked the whisper.cpp underlying library and it seems that as long as the segment is longer than duration, the full segment is retrieved (not only the specified duration).

https://github.com/ggerganov/whisper.cpp/


I recommend you open an issue directly there, as unfortunately, it cannot be fixed from this wrapper:
![image](https://user-images.githubusercontent.com/40202887/235300662-160763c5-b82b-46a4-ab5f-5dc76bed077e.png)
