### ISSUE TITLE
Severe hallucinations

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#202]
May I ask if there is a solution to the problem of hallucinations and particularly slow running in a CPU environment

**Comment by sandrohanea** [comment]
Probably it's mostly about hallucination on silence: https://github.com/ggerganov/whisper.cpp/issues/1724 
Regarding the inference speed, either use smaller models on CPU (e.g. Tiny) or use GPU/NPU runtimes if you have access to them
