### ISSUE TITLE
How to use the model ggml model gpt-2-345M. bin

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#203]
I find model in https://ggml.ggerganov.com/ ,but i dont know how to use

**Comment by sandrohanea** [comment]
Hello,
That's a GPT model (text to text), not a Whisper model (speech to text) and it cannot be executed with Whisper.net

There is this GPT-2 example in Whisper.cpp but it's quite outdated: https://github.com/ggerganov/whisper.cpp/blob/master/examples/talk/gpt-2.cpp

For up-to-date LLM inference, I recommend you take a look at: https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#description with dotnet bindings https://github.com/SciSharp/LLamaSharp

That should get you up to date quite fast with LLM inference.

**Comment by dfengpo** [comment]
Thank you,I have used LLamaSharp
