### ISSUE TITLE
using the VAD call processAsync by samples incorrect

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#206]
After using the VAD model to segment the recording, I called the ProcessAsync method with samples from a small segment of the recording, but the recognition result was incorrect.

But I passed all samples through SelectMany (x=>x) After ToArray() is connected, it can be successfully processed.

But after running for a period of time, the hallucinations became severe.Repeatedly output the following content
![image](https://github.com/sandrohanea/whisper.net/assets/12029452/c355759d-15b2-4ac9-8d53-401fb1e88048)

**Comment by sandrohanea** [comment]
This doesn't sound like a problem with Whisper.net but either with [whisper.cpp](https://github.com/ggerganov/whisper.cpp) or with the model weights. 

Please, check with latest version (1.7.0) and also compare it with whisper.cpp. If the issue reproduced only with whisper.net, it might be that some parameters are different and should be able to investigate. Feel free to reopen if that is the case.
