### ISSUE TITLE
The CPU is running too slowly in large v3

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#207]
Does it support running under GPU? The CPU is running too slowly in large v3

**Comment by sandrohanea** [comment]
Yes, it supports different GPU runtimes, check: 
https://github.com/sandrohanea/whisper.net/tree/main/examples/NvidiaCuda for NVidia GPU
https://github.com/sandrohanea/whisper.net/tree/main/examples/OpenVinoExample 
https://github.com/sandrohanea/whisper.net/tree/main/examples/Vulkan

Make sure you install all the drivers and the runtimes for each platform if Vulkan or OpenVino is used: https://github.com/sandrohanea/whisper.net/tree/main?tab=readme-ov-file#gpu-support
