### ISSUE TITLE
Why does the recognized text lack punctuation marks?

### ISSUE THREAD

**Issue by billqu01** [sandrohanea/whisper.net#209]
My partial code is as follows

var ggmlType = GgmlType.Medium;
var model_folder = System.IO.Path.GetDirectoryName(System.Windows.Forms.Application.ExecutablePath);
var modelFileName = model_folder + System.IO.Path.DirectorySeparatorChar + "ggml-medium.bin";

try
{
    var whisperFactory = WhisperFactory.FromPath(modelFileName, useGpu: true);

    using var processor = whisperFactory.CreateBuilder()
        .WithLanguage("zh")
        .Build();

How to modify the code?

**Comment by sandrohanea** [comment]
Unfortunately I cannot help with this. Looks like a problem with the Chinese language (that is probably with the model weights itself). 
This library is mostly a wrapper for [whisper.cpp](https://github.com/ggerganov/whisper.cpp/tree/master) which just uses the weights from OpenAI. Please, feel free to reopen if you think this is a problem with this library (if  [whisper.cpp](https://github.com/ggerganov/whisper.cpp/tree/master)  examples will provide punctuation marks) but this not, as we can investigate the parameters, but I don't see anything clear to it.
