### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by DVaughan** [sandrohanea/whisper.net#21]
Thanks for creating this project!
I'd like to use it in an Android app with Maui. Are you planning to add support for Android?

**Comment by sandrohanea** [comment]
Yes, it should be possible to be adapted and used from Maui and it sounds like a nice enhancement.

**Comment by sandrohanea** [comment]
Good news @DVaughan ,
@drasticactions added support for Android (among other platforms) in #30 
It will be a breaking change (as it will require a new Nuget package) and it will be probably only released in 1.4.0, but the support is definitely coming soon.

**Comment by DVaughan** [comment]
Very nice! Thanks for the heads up @sandrohanea.
