### ISSUE TITLE
Example Cublas canot work

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#211]
I debug cublas example code by large-v3 model on local, it dont work
Failed to load native whisper library. Error: 找不到指定的模块。

   在 Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit, String libraryPath, Boolean bypassLoading)
   在 Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization, String libraryPath, Boolean bypassLoading, Boolean useGpu)
   在 Program.<Main>d__0.MoveNext() 在 whisper.net\examples\Cublas\Program.cs 中: 第 32 行

**Comment by sandrohanea** [comment]
Please, check the latest version (1.7.0) with Whisper.net.Runtime.Cuda package. Make sure you have the latest Nvidia drivers installed.

This is an example of the usage:
https://github.com/sandrohanea/whisper.net/tree/main/examples/NvidiaCuda

This should be the output:
![image](https://github.com/user-attachments/assets/d2c77570-b371-4b0a-99c2-cf4105aeeca8)

**Comment by dfengpo** [comment]
thank you
