### ISSUE TITLE
System.Runtime.InteropServices.SEHException on non-AVX CPU

### ISSUE THREAD

**Issue by IMikkeI** [sandrohanea/whisper.net#239]
Hello, 

I'm currently developing a program to run on a non-AVX CPU. I have installed the _Whisper.net.AllRuntimes_ package and explicitly used _RuntimeLibrary.CpuNoAvx_.

I get an exception when calling the _WhisperFactory.FromPath(modelName)_ method.

The exception is as follows: **System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'** If I go down the stack trace, the exception comes from the public _nint LoadNativeContext(INativeWhisper nativeWhisper)_ method from _WhisperProcessorModelFileLoader_ class.

Is this a known error, or is there any way of finding the cause?

Thanks in advance for your help

Mickaël

**Comment by sandrohanea** [comment]
Hey @IMikkeI ,
There are indeed some problems with non-AVX runtimes, see the associated PR in whisper.cpp but also: https://github.com/sandrohanea/whisper.net/pull/240

The problems are:
 - Windows Build machine with AVX support always created AVX-Enabled runtime (Fixing it with the PR in whisper.cpp)
 - Linux build for noavx had a config issue with the destination path and was not included in the Whisper.net.Runtime.NoAvx package
 
Working on it and will update as soon as possible.

**Comment by sandrohanea** [comment]
Hey @IMikkeI ,
Can you, please, check 1.7.2-preview2 to see if it works as expected on your system?

Thank you!

**Comment by IMikkeI** [comment]
Hello @sandrohanea,

I've just tested this version and it corrects the error I had. 

I have an additional question: on my development machine which supports avx instructions and for the same audio file, I go from 1 second to 19 seconds when explicitly using the NoAvx runtime. Is this difference in performance consistent?

Thanks you again!

**Comment by sandrohanea** [comment]
Unfortunately, yes, that is expected based on my tests as well. However, if you have any special instructions on your target machine (e.g. FMA, AVX, F16C) those won't be used with NoAvx runtime. 

The best performance if you have any of those, but not others, can be archived if building the whisper.cpp runtime on the target machine with `GGML_NATIVE=ON`. This way, the optimization will be detected and used. 

For the available optimizations, see: https://github.com/ggerganov/whisper.cpp/blob/0377596b77a3602e36430320cbe45f8c305ef04a/ggml/CMakeLists.txt#L96

For building the native runtime, see our https://github.com/sandrohanea/whisper.net/blob/main/Makefile and https://github.com/sandrohanea/whisper.net/blob/main/windows-scripts.ps1

**Comment by IMikkeI** [comment]
Thank you @sandrohanea for all these details
