### ISSUE TITLE
System.ArgumentException: Invalid path

### ISSUE THREAD

**Issue by Senior-S** [sandrohanea/whisper.net#243]
Whisper version: Whiper.Net 1.7.1 on net standard 2.1
Full error: https://paste.gg/p/anonymous/7d6abdc7db0247739a7b7c63e1a04991
I'm trying to use the library on Windows 11, specifically as a plugin for a Unity mono game, but everytime I try to load the WhisperFactory it throws the Invalid Path error, I confirmed that the file exists and the plugin have read/write access to the folder where it's located, still the same error.

Code: https://paste.gg/p/anonymous/40e5dbdd194d44739d0350551b46ed6b
btw path field is: 
```
string path = $"{Environment.CurrentDirectory}/Plugins/Test/ggml-base.bin";
```

I'm doing something wrong?

**Comment by sandrohanea** [comment]
Hello @Senior-S ,
It seems that the error is when loading the native library, not when loading the model. 

You can try to use `1.7.2-preview1` where I added some extra logs around library loading.

In order to enable the logs, you can call `LogProvider.AddConsoleLogging(minLevel: WhisperLogLevel.Debug);` before creating any WhisperFactory in order to write the logs to Console.

You can also use `LogProvider.Instance.OnLog += (...)` to define custom logic for your logs.

Based on the stacktrace, the error is at one of these `Path.GetDirectoryName` https://github.com/sandrohanea/whisper.net/blob/5ddb2c7810e100b71bf70f576bd6a76bfa56cb16/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L192

This looks indeed like a bug in the library for that type of application (Unity mono game) where either ` Path.GetDirectoryName(typeof(NativeLibraryLoader).Assembly.Location)` or `Path.GetDirectoryName(Environment.GetCommandLineArgs()[0])` throws that exception.

Can you, please, try to run only these 2 in your app and identify which one crashes?

Will apply a fix anyway (to ensure that the path is checked before that retrieval).

**Comment by Senior-S** [comment]
Hi, thanks for the fast reply!
The issue seems to be with the NativeLibraryLoader.
```
Test >> Testing typeof(NativeLibraryLoader).Assembly.Location
Failed to load Test, unloading now... :System.ArgumentException: Invalid path
  at System.IO.Path.GetDirectoryName (System.String path) [0x0000d] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at Test.Test.Load () [0x000c2] in <950428785d174265a9108f0fd9f9bc81>:0
  ```
Using `Path.GetDirectoryName(Environment.GetCommandLineArgs()[0])` works fine:
```
Test >> Testing Environment.GetCommandLineArgs()[0]
Test >> Done
```

**Comment by sandrohanea** [comment]
It's on nuget but you'll need to check for preview versions: https://www.nuget.org/packages/Whisper.net/1.7.2-preview1
![image](https://github.com/user-attachments/assets/eafecb4b-8786-442b-a1e8-8ac6ca449f5b)

Out of curiosity, what is the returned string for `typeof(NativeLibraryLoader).Assembly.Location` for your environment?

**Comment by Senior-S** [comment]
The result of `typeof(NativeLibraryLoader).Assembly.Location` is an empty string.
On version 1.7.2-preview1 still have the same error:
```
System.ArgumentException: Invalid path
  at System.IO.Path.GetDirectoryName (System.String path) [0x0000d] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at Whisper.net.LibraryLoader.NativeLibraryLoader+<GetRuntimePaths>d__4.MoveNext () [0x000b5] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <d61464951b0243f18092630834a7bf18>:0
  at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent () [0x000c3] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary () [0x00042] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at Whisper.net.WhisperFactory+<>c.<.cctor>b__10_0 () [0x00000] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at System.Lazy`1[T].CreateValue () [0x00074] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at System.Lazy`1[T].get_Value () [0x0000a] in <47fc8c70fa834cbf8141d7c1a7589125>:0
  at Whisper.net.WhisperFactory..ctor (Whisper.net.Internals.ModelLoader.IWhisperProcessorModelLoader loader, System.Boolean delayInit) [0x00013] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at Whisper.net.WhisperFactory.FromPath (System.String path, System.Boolean delayInitialization) [0x00006] in <0fcf4b09a8c449f995c15861c2c49362>:0
  at Test.Test.InCodeTranscribe (System.String filePath) [0x000de] in <84098ccded7b4138b5bef101e3c68e6c>:0
  ```
 I added the console logging before creating a new WhisperFactory, but no extra errors were logged.
 ```
 LogProvider.Instance.OnLog += (level, message) =>
{
    Logger.Log($"{level} {message}");
};
LogProvider.AddConsoleLogging(minLevel: WhisperLogLevel.Debug);
```

**Comment by sandrohanea** [comment]
Interesting, it seems that Path.GetDirectoryName is crashing on net framework, Net core <2.1 and probably mono if empty string is provided, but returns null on newer dotnet versions.
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getdirectoryname?view=net-8.0
![image](https://github.com/user-attachments/assets/a0df20b9-40a9-4303-9192-a90b243bb122)

**Comment by sandrohanea** [comment]
It was closed automatically when the fix was merged, but it is not yet released, so I'll re-open the issue.
Will close when a preview version will be available (hopefully soon)

**Comment by Senior-S** [comment]
Ok, thank you so much!

**Comment by sandrohanea** [comment]
Hey @Senior-S ,
Version 1.7.2-preview2 is now released on nuget. that should fix your issue. Can you, please, confirm?

**Comment by Senior-S** [comment]
It works!
I have another problem now tho:
```
Whisper.net.Wave.CorruptedWaveException: Unsupported wave file
  at Whisper.net.Wave.WaveParser.InternalInitialize (System.Boolean useAsync, System.Threading.CancellationToken cancellationToken) [0x003b9] in <e67d36d6e36949c185d2409064f3e977>:0
  at Whisper.net.Wave.WaveParser.GetAvgSamplesAsync (System.Threading.CancellationToken cancellationToken) [0x0007a] in <e67d36d6e36949c185d2409064f3e977>:0
  at Whisper.net.WhisperProcessor+<ProcessAsync>d__25.MoveNext () [0x000b1] in <e67d36d6e36949c185d2409064f3e977>:0
  at Whisper.net.WhisperProcessor+<ProcessAsync>d__25.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult (System.Int16 token) [0x00000] in <e67d36d6e36949c185d2409064f3e977>:0
  at Test.Test.Transcribe (System.String filePath) [0x0018f] in <df3910f189914fa1b468f932dfcbc092>:0
  at Test.Test.Transcribe (System.String filePath) [0x0024d] in <df3910f189914fa1b468f932dfcbc092>:0
  ```
  The wav file I'm using is 24000 of sample rate, 32 of bit rate, should it be a different?

**Comment by sandrohanea** [comment]
The problem seems to be with the wave format. Our current parser supports only PCM for now:

https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/Wave/WaveParser.cs#L357

You can reformat it using NAudio (we have some examples for it)

**Comment by Senior-S** [comment]
Oh I see, my bad, thank you so much

**Comment by ZhenyaPav** [comment]
I am having a very similar issue on Godot, linux. I am running it with dotnet 9, loading the libraries automatically fails, as far as I can tell due to `Environment.GetCommandLineArgs()` being empty. `typeof(NativeLibraryLoader).Assembly.Location` is also empty.

I tried to use dlopen from my code:
```
    [DllImport("libdl.so.2")]
    private static extern IntPtr dlopen(string fileName, int flag);
    [DllImport("libdl.so.2")]
    private static extern IntPtr dlerror();

...
        string libggmlPath = FindFile(Directory.GetCurrentDirectory(), "libggml-whisper.so");
        GD.Print(typeof(NativeLibraryLoader).Assembly.Location);


        string libDir = Path.GetDirectoryName(libggmlPath);
        GD.Print(dlopen(libggmlPath, 0x00002).ToString());
        string libwhisperPath = Path.Combine(libDir, "libwhisper.so");
        GD.Print(libwhisperPath);
        GD.Print(dlopen(libwhisperPath, 0x00002).ToString());


        RuntimeOptions.Instance.SetLoadedLibrary(RuntimeLibrary.Cpu);
        RuntimeOptions.Instance.SetBypassLoading(true);
        whisperFactory = WhisperFactory.FromPath("ggml-base.bin");


```
 but it still throws an error:
```
E 0:00:01:0291   void Whisper.net.Internals.Native.Implementations.LibraryImportLibWhisper.whisper_log_set(nint, nint): System.DllNotFoundException: Unable to load shared library 'libwhisper' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/libwhisper.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/liblibwhisper.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/libwhisper: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/liblibwhisper: cannot open shared object file: No such file or directory

  <C++ Error>    System.DllNotFoundException
  <C++ Source>   :0 @ void Whisper.net.Internals.Native.Implementations.LibraryImportLibWhisper.whisper_log_set(nint, nint)
  <Stack Trace>  :0 @ void Whisper.net.Internals.Native.Implementations.LibraryImportLibWhisper.whisper_log_set(nint, nint)
                 :0 @ void Whisper.net.Logger.LogProvider.InitializeLogging(Whisper.net.Internals.Native.INativeWhisper)
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.WhisperFactory+<>c.<.cctor>b__13_0()
                 :0 @ void System.Lazy`1.ViaFactory(System.Threading.LazyThreadSafetyMode)
                 :0 @ void System.Lazy`1.ExecutionAndPublication(System.LazyHelper, bool)
                 :0 @ T System.Lazy`1.CreateValue()
                 :0 @ void Whisper.net.WhisperFactory.CheckLibraryLoaded()
                 :0 @ Whisper.net.WhisperFactory..ctor(Whisper.net.Internals.ModelLoader.IWhisperProcessorModelLoader, bool)
                 :0 @ Whisper.net.WhisperFactory Whisper.net.WhisperFactory.FromPath(string, bool)
                 SpeechToText.cs:65 @ void SpeechToText+<_Ready>d__11.MoveNext()
                 :0 @ void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                 :0 @ void System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(object)
                 GodotSynchronizationContext.cs:51 @ void Godot.GodotSynchronizationContext.ExecutePendingContinuations()
                 GodotTaskScheduler.cs:76 @ void Godot.GodotTaskScheduler.Activate()
                 ScriptManagerBridge.cs:84 @ void Godot.Bridge.ScriptManagerBridge.FrameCallback()
```

**Comment by sandrohanea** [comment]
Hello @ZhenyaPav ,

The best would be to open a new issue for the whisper.net with godot issues that you're facing.

On short: I don't recommend to set bypass loading to true if you just want to load default librairies (when we'll update to 1.7.4 it will include more dependencies that you'll need to load manually).

However, if you want to test the library until that issue with EnvironmentVariable is fixed, you'll need probably to use `0x00102` flag (which is RTLD_NOW + RTLD_GLOBAL), as just NOW is not enough. RTLD_GLOBAL: Makes the symbols from the loaded library available for symbol resolution in subsequently loaded libraries (which will be used by the DllImport v/ LIbrayImport code later)
