### ISSUE TITLE
Incompatibility with LLamaSharp

### ISSUE THREAD

**Issue by Lyrcaxis** [sandrohanea/whisper.net#251]
Seems there's an incompatibility with LLamaSharp after latest updates; It appears impossible to have them both loaded at the same time no matter what libraries/backends you specify or in what order you load them up. I drafted a minimal reproduction snippet:

```cs
// NOTE: If you only call a single method, it'll work.
void StartupWhisper() {
    RuntimeOptions.Instance.SetLibraryPath(@"dlls\whisper.dll"); // or comment out
    var whisperFactory = WhisperFactory.FromPath("");
}

void StartupLLamaSharp() {
    NativeLibraryConfig.LLama.WithLibrary(@"dlls\llama.dll"); // or comment out
    var modelParams = new ModelParams("");
}

void StartupBoth_WhisperFirst() { SetupWhisperModel(); SetupLLamaSharpModel(); } // Throws from LLamaSharp
void StartupBoth_LLamaFirst()   { SetupLLamaSharpModel(); SetupWhisperModel(); } // Throws from Whisper.net
```

I assume that because both `llama.dll` and `whisper.dll` depend on `ggml.dll`, the `llama.dll` and `whisper.dll` just check on the already loaded ggml of the other library, disregarding versioning.

Is this something that any one of `[LLamaSharp, Whisper.net]` can fix by itself? Aka make its dependencies standalone.

###### PS: I've cross-posted this in the `LLamaSharp` repo to link in case it needs back and forth: https://github.com/SciSharp/LLamaSharp/issues/974

**Comment by sandrohanea** [comment]
Hello @Lyrcaxis ,
Indeed, interesting issue.

Unless LlamaSharp and Whisper.net will use the same ggml version. which is hard to maintain as long term solution, I think we can change the name of the ggml.dll used by whisper.net to ggml-whisper.dll.

This way, we'll have 2 dlls:
- whisper.dll
- ggml-whisper.dll

And will ensure that the ggml library won't be used by LlamaSharp and they will load their own.

Will create a PR and release this version soon.

**Comment by Lyrcaxis** [comment]
Hi, I'm very glad to hear that! I was afraid there was some internal `whisper.cpp` trickery that would expect strongly-named dll-method combinations and it would be an unreasonable amount of work. Great job at resolving that, and thanks!

**Comment by sandrohanea** [comment]
Version 1.7.2-preview3 should be created soon and pushed to nuget that will have this change: https://github.com/sandrohanea/whisper.net/actions/runs/11693191206

`whisper.dll` now depends on `ggml-whisper.dll`:
![image](https://github.com/user-attachments/assets/ad1deb99-7afb-4980-85f4-3a2534d45cf0)


The only downside that I see is that if someone wants to use both Whisper.net and LlamaSharp with Cuda backend, the runtimes for ggml will be quite big (1.2 GB => 300MB Whisper Windows, 300MB Whisper Linux, 300MB Llama Windows and 300MB Llama Linux)

If someone will really have this problem and they will need only one ggml reference, they can create a single package for both Llama backend and Whisper Runtime and load it manually. (with BypassLoading in Whisper.net).

**Comment by Lyrcaxis** [comment]
After the new update it works like a charm! Thanks for the quick and effective patch!
The file-size when built is indeed ~700MB per target backend/OS combo, but it's indeed insignificant with modern hardware.
