### ISSUE TITLE
whisper.net.runtime.cuda\1.7.1 can not work

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#254]
I use whisper.net.runtime.cuda\1.7.1，on linux and got this error,
How to sovle it?

Unhandled exception. System.IO.FileNotFoundException: Native Library not found in default paths.Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
   at Whisper.net.WhisperFactory.<>c.<.cctor>b__10_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at Program.Main(String[] args) in D:\github\Whisper\whisper.net\examples\NvidiaCuda\Program.cs:line 32
   at Program.<Main>(String[] args)
Aborted (core dumped)

**Comment by dfengpo** [comment]
This is my driver
![image](https://github.com/user-attachments/assets/e5f4895e-93af-4931-97af-1c1688621bb9)

**Comment by sandrohanea** [comment]
In order to enable the debug logs, you can call LogProvider.AddConsoleLogging(minLevel: WhisperLogLevel.Debug); before creating any WhisperFactory in order to write the logs to Console.

That should show you which native library is loaded and why.

**Comment by dfengpo** [comment]
Ok,this is my logs like this:
@sandrohanea 

Debug: Searching for runtime directory Cuda in /app/asr-whisper-test/runtimes/cuda/linux-x64
Debug: Searching for runtime directory Cuda in /app/asr-whisper-test/runtimes/cuda/linux-x64
Debug: Searching for runtime directory Vulkan in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Runtime directory for Vulkan not found in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Searching for runtime directory Vulkan in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Runtime directory for Vulkan not found in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Searching for runtime directory CoreML in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Runtime directory for CoreML not found in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Searching for runtime directory CoreML in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Runtime directory for CoreML not found in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Searching for runtime directory OpenVino in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Runtime directory for OpenVino not found in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Searching for runtime directory OpenVino in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Runtime directory for OpenVino not found in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Searching for runtime directory Cpu in /app/asr-whisper-test/runtimes/linux-x64
Debug: Runtime directory for Cpu not found in /app/asr-whisper-test/runtimes/linux-x64
Debug: Searching for runtime directory Cpu in /app/asr-whisper-test/runtimes/linux-x64
Debug: Runtime directory for Cpu not found in /app/asr-whisper-test/runtimes/linux-x64
Debug: Searching for runtime directory CpuNoAvx in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Runtime directory for CpuNoAvx not found in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Searching for runtime directory CpuNoAvx in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Runtime directory for CpuNoAvx not found in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Checking if runtime Cuda is supported on the platform: linux
Debug: Checking for CUDA availability.
Debug: Cudart library couldn't be loaded.
Debug: Cuda driver is not available or no cuda device is identified.
Debug: Checking if runtime Cuda is supported on the platform: linux
Debug: Checking for CUDA availability.
Debug: Cudart library couldn't be loaded.
Debug: Cuda driver is not available or no cuda device is identified.
Unhandled exception. System.IO.FileNotFoundException: Native Library not found in default paths.Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
   at Whisper.net.WhisperFactory.<>c.<.cctor>b__12_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Whisper.net.WhisperFactory.CheckLibraryLoaded()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at Program.Main(String[] args) in D:\github\Whisper\whisper.net\examples\NvidiaCuda\Program.cs:line 38
   at Program.<Main>(String[] args)
Aborted (core dumped)

**Comment by sandrohanea** [comment]
It seems your system is missing cudart based on the logs:

Cudart library couldn't be loaded.

Please, ensure cuda driver is installed with cudart component.

**Comment by dfengpo** [comment]
Thanks.
Can you run on docker image of nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04?
My drive is NVIDIA-SMI 535.183.01 Driver Version: 535.183.01 CUDA Version: 12.2
I found libcudart.so.11.0  and libcudart.so.11.8.89 on /usr/local/cuda/lib64

`root@3a4a73a26102:/usr/local/cuda# ls lib64
libOpenCL.so.1            libcufft.so.10.9.0.58    libcusolver.so.11.4.1.48    libnppicc.so.11.8.0.86   libnppist.so.11.8.0.86  libnvblas.so.11
libOpenCL.so.1.0          libcufftw.so.10          libcusolverMg.so.11         libnppidei.so.11         libnppisu.so.11         libnvblas.so.11.11.3.6
libOpenCL.so.1.0.0        libcufftw.so.10.9.0.58   libcusolverMg.so.11.4.1.48  libnppidei.so.11.8.0.86  libnppisu.so.11.8.0.86  libnvjpeg.so.11
libcublas.so.11           libcufile.so.0           libcusparse.so.11           libnppif.so.11           libnppitc.so.11         libnvjpeg.so.11.9.0.86
libcublas.so.11.11.3.6    libcufile.so.1.4.0       libcusparse.so.11.7.5.86    libnppif.so.11.8.0.86    libnppitc.so.11.8.0.86  libnvrtc-builtins.so.11.8
libcublasLt.so.11         libcufile_rdma.so.1      libnppc.so.11               libnppig.so.11           libnpps.so.11           libnvrtc-builtins.so.11.8.89
libcublasLt.so.11.11.3.6  libcufile_rdma.so.1.4.0  libnppc.so.11.8.0.86        libnppig.so.11.8.0.86    libnpps.so.11.8.0.86    libnvrtc.so.11.2
libcudart.so.11.0         libcurand.so.10          libnppial.so.11             libnppim.so.11           libnvToolsExt.so        libnvrtc.so.11.8.89
libcudart.so.11.8.89      libcurand.so.10.3.0.86   libnppial.so.11.8.0.86      libnppim.so.11.8.0.86    libnvToolsExt.so.1
libcufft.so.10            libcusolver.so.11        libnppicc.so.11             libnppist.so.11          libnvToolsExt.so.1.0.0
root@3a4a73a26102:/usr/local/cuda# `

**Comment by dfengpo** [comment]
@sandrohanea 
Thanks.
Can you run on docker image of nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04?
My drive is NVIDIA-SMI 535.183.01 Driver Version: 535.183.01 CUDA Version: 12.2
I found libcudart.so.11.0 and libcudart.so.11.8.89 on /usr/local/cuda/lib64.
When i copy "libcudart.so.11.0" and rename to "libcudart.so",
I got this error "Failed to load ggml library from /app/asr-whisper-test/runtimes/cuda/linux-x64/libggml-whisper.so. Error: Cannot load the library on this platform using NativeLibrary"
libggml-whisper.so which platforms are supported?

Debug: Searching for runtime directory Cuda in /app/asr-whisper-test/runtimes/cuda/linux-x64
Debug: Searching for runtime directory Cuda in /app/asr-whisper-test/runtimes/cuda/linux-x64
Debug: Searching for runtime directory Vulkan in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Runtime directory for Vulkan not found in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Searching for runtime directory Vulkan in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Runtime directory for Vulkan not found in /app/asr-whisper-test/runtimes/vulkan/linux-x64
Debug: Searching for runtime directory CoreML in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Runtime directory for CoreML not found in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Searching for runtime directory CoreML in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Runtime directory for CoreML not found in /app/asr-whisper-test/runtimes/coreml/linux-x64
Debug: Searching for runtime directory OpenVino in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Runtime directory for OpenVino not found in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Searching for runtime directory OpenVino in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Runtime directory for OpenVino not found in /app/asr-whisper-test/runtimes/openvino/linux-x64
Debug: Searching for runtime directory Cpu in /app/asr-whisper-test/runtimes/linux-x64
Debug: Runtime directory for Cpu not found in /app/asr-whisper-test/runtimes/linux-x64
Debug: Searching for runtime directory Cpu in /app/asr-whisper-test/runtimes/linux-x64
Debug: Runtime directory for Cpu not found in /app/asr-whisper-test/runtimes/linux-x64
Debug: Searching for runtime directory CpuNoAvx in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Runtime directory for CpuNoAvx not found in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Searching for runtime directory CpuNoAvx in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Runtime directory for CpuNoAvx not found in /app/asr-whisper-test/runtimes/noavx/linux-x64
Debug: Checking if runtime Cuda is supported on the platform: linux
Debug: Checking for CUDA availability.
Debug: NUmber of CUDA devices found: 1
Debug: Trying to load ggml library from /app/asr-whisper-test/runtimes/cuda/linux-x64/libggml-whisper.so
Debug: Failed to load ggml library from /app/asr-whisper-test/runtimes/cuda/linux-x64/libggml-whisper.so. Error: Cannot load the library on this platform using NativeLibrary
Debug: Checking if runtime Cuda is supported on the platform: linux
Debug: Checking for CUDA availability.
Debug: NUmber of CUDA devices found: 1
Debug: Trying to load ggml library from /app/asr-whisper-test/runtimes/cuda/linux-x64/libggml-whisper.so
Debug: Failed to load ggml library from /app/asr-whisper-test/runtimes/cuda/linux-x64/libggml-whisper.so. Error: Cannot load the library on this platform using NativeLibrary
Unhandled exception. System.Exception: Failed to load native whisper library. Error: Cannot load the library on this platform using NativeLibrary
   at Whisper.net.WhisperFactory.CheckLibraryLoaded()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at Program.Main(String[] args) in D:\github\Whisper\whisper.net\examples\NvidiaCuda\Program.cs:line 38
   at Program.<Main>(String[] args)
Aborted (core dumped)
root@3a4a73a26102:/app/asr-whisper-test#

**Comment by dfengpo** [comment]
Do I need to install any more dependencies？

**Comment by sandrohanea** [comment]
Version 12 is required, not 11. As described: https://github.com/sandrohanea/whisper.net?tab=readme-ov-file#pre-requisites-2
I see that you logged https://github.com/sandrohanea/whisper.net/issues/257 so I suppose you managed to install it, so will close this issue.

**Comment by ProCheng** [comment]
How to solve the problem?
