### ISSUE TITLE
Vulkan linux runtime nuget?

### ISSUE THREAD

**Issue by dusanpol** [sandrohanea/whisper.net#264]
Hi, is it possible to publish linux version of Vulkan runtime nuget like it is the case for Cuda? I have been trying to compile Vulkan version of whisper.cpp so I can use my existing whisper.net code, but to no avail, my weak C++ skills let me down. The windows Vulkan runtime works fine.

**Comment by sandrohanea** [comment]
Hello @dusanpol,
Indeed, Vulkan runtime for Whisper.net is not yet available on linux.
Worked a bit on it but put it on pause. Will update here once it will be available.

**Comment by ZhenyaPav** [comment]
@sandrohanea Do you know if the vulkan runtime will work on Linux at all (in CPU-only mode), or it will error out?

**Comment by sandrohanea** [comment]
> @sandrohanea Do you know if the vulkan runtime will work on Linux at all (in CPU-only mode), or it will error out?

Yes, I expect it would work once someone adds the actions to build it + consumers of the library will have installed all the dependencies.

**Comment by sandrohanea** [comment]
A preview version should be available soon with Vulkan support for Linux x64: https://github.com/sandrohanea/whisper.net/actions/runs/12038208433

Ensure you have vulkan runtime installed and accessible in the path + vulkan drivers.

**Comment by sandrohanea** [comment]
Hey @ZhenyaPav, @dusanpol ,
Have you had any chance to check Whisper.net.Vulkan 1.7.3-preview1 ?
https://www.nuget.org/packages/Whisper.net.Runtime.Vulkan/1.7.3-preview1

I don't have a linux host with vulkan drivers, but it should be available now (assuming you have the drivers, and the toolkit installed).

**Comment by dusanpol** [comment]
I tried it, unfortunately nuget package only contains win-x64 DLLs, so build fails with these errors:
```
/usr/lib/dotnet/sdk/9.0.100/Microsoft.Common.CurrentVersion.targets(5322,5): error MSB3030: Could not copy the file "/home/dusanpol/.nuget/packages/whisper.net.runtime.vulkan/1.7.3-preview1/build/linux-x64/libwhisper.so" because it was not found.
/usr/lib/dotnet/sdk/9.0.100/Microsoft.Common.CurrentVersion.targets(5322,5): error MSB3030: Could not copy the file "/home/dusanpol/.nuget/packages/whisper.net.runtime.vulkan/1.7.3-preview1/build/linux-x64/libggml-whisper.so" because it was not found.
```

**Comment by sandrohanea** [comment]
Indeed, it seems that CD workflow was not triggering linux-vulkan build :(
Addressing it in: https://github.com/sandrohanea/whisper.net/pull/284
Thanks for the quick check @dusanpol !

**Comment by sandrohanea** [comment]
> I tried it, unfortunately nuget package only contains win-x64 DLLs, so build fails with these errors:
> 
> ```
> /usr/lib/dotnet/sdk/9.0.100/Microsoft.Common.CurrentVersion.targets(5322,5): error MSB3030: Could not copy the file "/home/dusanpol/.nuget/packages/whisper.net.runtime.vulkan/1.7.3-preview1/build/linux-x64/libwhisper.so" because it was not found.
> /usr/lib/dotnet/sdk/9.0.100/Microsoft.Common.CurrentVersion.targets(5322,5): error MSB3030: Could not copy the file "/home/dusanpol/.nuget/packages/whisper.net.runtime.vulkan/1.7.3-preview1/build/linux-x64/libggml-whisper.so" because it was not found.
> ```

Hey @dusanpol ,
The new version 1.7.3-preview2 is available now on nuget with the fix for the nuget package to include those files.

**Comment by dusanpol** [comment]
Looks good to me 👍 Tested on WAN Show.
![image](https://github.com/user-attachments/assets/3abcbe90-82ff-4927-a009-a8ed97c9fdaf)

**Comment by sandrohanea** [comment]
1.7.3 was released with support for Vulkan Linux 🎉

**Comment by ZhenyaPav** [comment]
> Hey @ZhenyaPav, @dusanpol , Have you had any chance to check Whisper.net.Vulkan 1.7.3-preview1 ? https://www.nuget.org/packages/Whisper.net.Runtime.Vulkan/1.7.3-preview1
> 
> I don't have a linux host with vulkan drivers, but it should be available now (assuming you have the drivers, and the toolkit installed).

@sandrohanea  Sorry for the late reply, me and my team tried it out today. Worked on Windows, but on Linux I'm having this error:

```
E 0:00:01:0509   bool Whisper.net.LibraryLoader.NativeLibraryLoader+<GetRuntimePaths>d__4.MoveNext(): System.IndexOutOfRangeException: Index was outside the bounds of the array.
  <C++ Error>    System.IndexOutOfRangeException
  <C++ Source>   :0 @ bool Whisper.net.LibraryLoader.NativeLibraryLoader+<GetRuntimePaths>d__4.MoveNext()
  <Stack Trace>  :0 @ bool Whisper.net.LibraryLoader.NativeLibraryLoader+<GetRuntimePaths>d__4.MoveNext()
                 :0 @ System.Collections.Generic.List`1..ctor(System.Collections.Generic.IEnumerable`1[T])
                 :0 @ System.Collections.Generic.List`1[TSource] System.Linq.Enumerable.ToList<TSource>(System.Collections.Generic.IEnumerable`1[TSource])
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.WhisperFactory+<>c.<.cctor>b__13_0()
                 :0 @ void System.Lazy`1.ViaFactory(System.Threading.LazyThreadSafetyMode)
                 :0 @ void System.Lazy`1.ExecutionAndPublication(System.LazyHelper, bool)
                 :0 @ T System.Lazy`1.CreateValue()
                 :0 @ void Whisper.net.WhisperFactory.CheckLibraryLoaded()
                 :0 @ Whisper.net.WhisperFactory..ctor(Whisper.net.Internals.ModelLoader.IWhisperProcessorModelLoader, bool)
                 :0 @ Whisper.net.WhisperFactory Whisper.net.WhisperFactory.FromPath(string, bool)
                 SpeechToText.cs:51 @ void SpeechToText+<_Ready>d__9.MoveNext()
                 :0 @ void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                 :0 @ void System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(object)
                 GodotSynchronizationContext.cs:51 @ void Godot.GodotSynchronizationContext.ExecutePendingContinuations()
                 GodotTaskScheduler.cs:76 @ void Godot.GodotTaskScheduler.Activate()
                 ScriptManagerBridge.cs:84 @ void Godot.Bridge.ScriptManagerBridge.FrameCallback()

```

**Comment by ZhenyaPav** [comment]
```
ERROR: System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLoadError()
   at Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLastError()
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
   at Whisper.net.WhisperFactory.<>c.<.cctor>b__13_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Whisper.net.WhisperFactory.CheckLibraryLoaded()
   at Whisper.net.WhisperFactory.GetRuntimeInfo()
   at SpeechToText._Ready() in /home/zhenyapav/Projects/ai-desktop-pet/Scripts/SpeechToText/SpeechToText.cs:line 44
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Godot.GodotSynchronizationContext.ExecutePendingContinuations()
   at Godot.GodotTaskScheduler.Activate()
   at Godot.Bridge.ScriptManagerBridge.FrameCallback()
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
```
An exception outside of the editor seems to be more useful. Looks like whisper.net tries to load `libdl`, which has been replaced by `libdl.so.2` on modern systems.

**Comment by ZhenyaPav** [comment]
The second issue seems to only be affecting godot projects when using dotnet6, the first one is also present with dotnet 9. Most likely an issue with godot itself, as the example project works fine

**Comment by ZhenyaPav** [comment]
I would appreciate any kind of help in making this library work. The runtime libraries are placed into a directory `data_AI_Desktop_Companion_linuxbsd_x86_64/runtimes` in a built project.

**Comment by ZhenyaPav** [comment]
I believe the error is due to `Environment.GetCommandLineArgs();` being empty in Godot.

**Comment by sandrohanea** [comment]
> An exception outside of the editor seems to be more useful. Looks like whisper.net tries to load `libdl`, which has been replaced by `libdl.so.2` on modern systems. I'll try to make a pull request that fixes it.

We are following the same support lifetime as dotnet: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Which means that support for dotnet 6 was removed. The version that you probably used (which is using libdl) is netstandard that is maintained for netframework support which is still supported and not near EOL: https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

However, same netstandard version can be used with out-of-date dotnet6 projects but that is not supported.

Regarding the first error, indeed we are getting the command line args and trying to use the first arg as a possible source of the runtime dir which is normally just the name of the executable (App Start Location):
https://github.com/sandrohanea/whisper.net/blob/0b9bb5d664fcb449d093155f0d52317bde3e8dca/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L192

Can you, please, confirm that following code will return you a path where you can find the runtimes dir in godot?

```
        var assemblyLocation = typeof(NativeLibraryLoader).Assembly.Location;
        var commandLineArgs =  Environment.GetCommandLineArgs().FirstOrDefault();
        // NetFramework and Mono will crash if we try to get the directory of an empty string.
        var assemblySearchPaths = new[]
            {
                GetSafeDirectoryName(RuntimeOptions.LibraryPath),
                AppDomain.CurrentDomain.RelativeSearchPath,
                AppDomain.CurrentDomain.BaseDirectory,
                GetSafeDirectoryName(assemblyLocation),
                GetSafeDirectoryName(environmentAppStartLocation),
            }.Where(it => !string.IsNullOrEmpty(it)).Distinct();

```
It would be better if you fill another issue for this godot problem, to not mix it up with vulkan runtime.

**Comment by ZhenyaPav** [comment]
Created #307 
With the exception not being thrown, `NativeLibraryLoader.GetRuntimePaths()` seems to return correct paths. Will do further testing.
