### ISSUE TITLE
I'm getting whisper_full_with_state: input is too short for short audio clips

### ISSUE THREAD

**Issue by kaniosm** [sandrohanea/whisper.net#265]
Whenever I try to transcribe short audio files, I get the below error, even after padding the audio with silence:
whisper_full_with_state: input is too short - xxx ms < 1000 ms. consider padding the input audio with silence

**To Reproduce**
1. Install version 1.7.2 (tested with 1.7.2 pre and 1.7.1 as well)
2. Transcribe short audio 

I tried setting the .WithoutSuppressBlank() option, but the result is still the same...
I use the below to pad the audio with silence:

var buffer = Convert.FromBase64String(request.AudioDataBase64);
int bytesPerMillisecond = 64;
var tot_ms = buffer.Length / bytesPerMillisecond;
if (tot_ms < 1000)
{
    var silentBytes = new byte[(1000 - tot_ms) * bytesPerMillisecond];
    buffer = [.. buffer, .. silentBytes];
}

**Comment by sandrohanea** [comment]
Hello @kaniosm ,
Yes, having a minimum of 1 second buffer is expected, and it is the default behavior in whisper.cpp: https://github.com/ggerganov/whisper.cpp/blob/1626b73b035ff9aa2b8d6d7bc9eccfdcd783be24/src/whisper.cpp#L5440

`WithoutSuppressBlank` is for blank outputs, not inputs.

It seems you are padding it, but I expect that it is not enough (you'll need at least 100 frames). I see you check with the buffer.Length, but I expect that will include the wave header (which doesn't have frames) so you still not add enough samples for silence with your code. 

Also, the number of bytesPerMilliseconds might be different based on the bitsPerSample and SampleRate (which should be 16k) 

More than that, the byte[] buffer will most likely be parsed with the WaveParser after that code, and if the header contains only the first samples (without the added suppressed ones) they will be simply ignored.
SamplesCount resulted after parsing a stream, depends on the:
https://github.com/sandrohanea/whisper.net/blob/76d9239d9ecce27f524c357ef934eb3678816a3e/Whisper.net/Wave/WaveParser.cs#L433

That is most likely embedded in the first buffer that you created and only contains the data without the added silence.


I suggest you to use the [WaveParser](https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/Wave/WaveParser.cs) and append the samples directly at the end, after the initial samples are parsed.

E.g.:

```
var buffer = Convert.FromBase64String(request.AudioDataBase64);
using var memoryStream = new MemoryStream(buffer);
var waveParser = new WaveParser(memoryStream);

// you can also just get the samples from specific channel
var samples = await waveParser.GetAvgSamplesAsync();

if (samples.Length < 100)
{
    var silentSamples = new float[100-samples.Length];
    samples = [..samples, ..silentSamples];
}

...
```

Note: The above code was not tested, it is just for exemplification.

Please, let me know if that worked for you, and if not, maybe provide some mini-project with a repro-code.

**Comment by sandrohanea** [comment]
I was not talking about NAudio Wave Parser, but the WaveParser inside the Whisper.net that will be used anyway to read the samples from any stream. 
WhisperProcessor is just using that if a stream is provided instead of a ReadOnlyMemory<float> for samples:

https://github.com/sandrohanea/whisper.net/blob/76d9239d9ecce27f524c357ef934eb3678816a3e/Whisper.net/WhisperProcessor.cs#L196C7-L196C53

**Comment by kaniosm** [comment]
Yes, I just noticed. Thx!
