### ISSUE TITLE
Working with MP3s

### ISSUE THREAD

**Issue by 7702244** [sandrohanea/whisper.net#27]
How can we use the library with MP3 files? At the moment when working with MP3, the error "Invalid wave file RIFF header" is thrown. The original Whisper supports MP3 files.

**Comment by Alumniminium** [comment]
Original whisper does not support mp3, some example scripts just include the ffmpeg decoding step.

**Comment by sandrohanea** [comment]
Hello @7702244,
@Alumniminium is right, Whisper as a model is only supporting wav. But you can use ffmpeg or NAudio to process other types.

I didn't want to introduce any additional dependency in the base package, but another package with NAudio integration (which will have dependency both NAudio and Whisper.net) would be great.

**Comment by GFNiko** [comment]
For example, I wrote an Adapter with FfMpegCore, which converts every given file to .wav with a 16kHz sampling rate. It saves the converted file to the origin's filename and changes its file extension to .wav. Just needed to install FfMpegCore via NuGet
```c#
FFMpegArguments
                    .FromFileInput(filePath)
                    .OutputToFile($"{outputFilePath}", true,
                        options => options
                            .ForceFormat("wav")
                            .WithAudioSamplingRate(16000))
                    .ProcessAsynchronously();
```

Works like a charm for me

**Comment by sandrohanea** [comment]
Added also an example of how to use NAudio in order to convert the mp3 to wav 16 khz and pass it to Whisper.net:
https://github.com/sandrohanea/whisper.net/blob/main/examples/NAudioMp3/Program.cs

Ofc, FFmpeg can be used instead as @GFNiko shown above.

**Comment by lmxin123** [comment]
However, NAudio does not support Linux as it integrates too many Windows related APIs

**Comment by abutir** [comment]
> Added also an example of how to use NAudio in order to convert the mp3 to wav 16 khz and pass it to Whisper.net: https://github.com/sandrohanea/whisper.net/blob/main/examples/NAudioMp3/Program.cs
> 
> Ofc, FFmpeg can be used instead as @GFNiko shown above.

The problem with the sample is that it expects the files to always be mp3 , however you might have a large set of content differing in types from ogg , wav , mp3 , m4a ..etc which each would need to be handled separately to convert to wav.

@GFNiko usage of ffmpeg would be the most best way to handle it

**Comment by sandrohanea** [comment]
> > Added also an example of how to use NAudio in order to convert the mp3 to wav 16 khz and pass it to Whisper.net: https://github.com/sandrohanea/whisper.net/blob/main/examples/NAudioMp3/Program.cs
> > Ofc, FFmpeg can be used instead as @GFNiko shown above.
> 
> The problem with the sample is that it expects the files to always be mp3 , however you might have a large set of content differing in types from ogg , wav , mp3 , m4a ..etc which each would need to be handled separately to convert to wav.
> 
> @GFNiko usage of ffmpeg would be the best way to handle it

Hey @abutir ,

Indeed, FFmpeg is the most general and versatile way to handle different types of media. However, FFmpeg is not compatible with the MIT license, so it cannot be included as part of Whisper.net.

Additionally, be cautious when working with various codecs (e.g., AAC) embedded in containers like M4A, as they may require royalty payments depending on usage.
