### ISSUE TITLE
Can support CUDA11？

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#295]
Can support CUDA11.x？

**Comment by sandrohanea** [comment]
We don't plan to support it with default nuget packages but you can build the runtime for CUDA on your own and bundle it with your app and Whisper.net.

Here is the github workflow that builds linux support on CUDA: https://github.com/sandrohanea/whisper.net/blob/2356c59d934f901cc6f20ccd025526b49ac59b74/.github/workflows/linux-cuda-native-build.yml#L26

And this is for windows:
https://github.com/sandrohanea/whisper.net/blob/2356c59d934f901cc6f20ccd025526b49ac59b74/.github/workflows/windows-cuda-native-build.yml#L28

You can fork the repo, change that value to your preffered CUDA version and build using github actions.

Once the build is finished, you can download the artifacts and place them in your solution and ensure that whisper.net will load them (eitehr by placing them in `runtimes/cuda/linux-x64` and `runtimes/cuda/win-x64` or preload it using [NativeLibrary.Load](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.load?view=net-9.0#system-runtime-interopservices-nativelibrary-load(system-string))

**Comment by dfengpo** [comment]
Thank you, I try now
