### ISSUE TITLE
.NET Maui Blazer Hybrid error targeting Android

### ISSUE THREAD

**Issue by StevePGLS** [sandrohanea/whisper.net#297]
I have a .NET Maui Blazer Hybrid multiplatform solution that uses Whisper.net.  

My app targeting the Windows architecture works with no problem.  However, I am having issues targeting Android on a virtual emulator.  It compiles and runs on the Android emulator up until Whisper.net is invoked to load the model.  Here is my code:

```
    private void LoadModel(string modelFilePath)
    {
        if (!File.Exists(modelFilePath))
        {
            throw new FileNotFoundException($"Model file not found: {modelFilePath}");
        }

        var bufferedModel = File.ReadAllBytes(modelFilePath);
        _factory = WhisperFactory.FromBuffer(bufferedModel);
    }
```

An exception is thrown on that last line:

_factory = WhisperFactory.FromBuffer(bufferedModel);

Here is the error:

[monodroid-assembly] open_from_bundles: failed to load assembly SlideService.dll
Loaded assembly: /data/data/com.companyname.slideguimauiblazor/files/.__override__/SlideService.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Whisper.net.dll
Loaded assembly: /data/data/com.companyname.slideguimauiblazor/files/.__override__/Whisper.net.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly NAudio.Wasapi.dll
[monodroid-assembly] open_from_bundles: failed to load assembly NAudio.Core.dll
Resolved pending breakpoint at 'SlideService.cs:43,1' to void SlideService.SlideService.LoadModel (string modelFilePath) [0x00001].
Resolved pending breakpoint at 'SlideService.cs:49,1' to void SlideService.SlideService.LoadModel (string modelFilePath) [0x00027].
Resolved pending breakpoint at 'SlideService.cs:48,1' to void SlideService.SlideService.LoadModel (string modelFilePath) [0x00020].
Loaded assembly: /data/data/com.companyname.slideguimauiblazor/files/.__override__/NAudio.Wasapi.dll [External]
Loaded assembly: /data/data/com.companyname.slideguimauiblazor/files/.__override__/NAudio.Core.dll [External]
[monodroid-assembly] Shared library 'libggml-whisper' not loaded, p/invoke 'ggml_log_set' may fail
[monodroid-assembly] Shared library 'libggml-whisper' not loaded, p/invoke 'ggml_log_set' may fail
...
[chromium] [INFO:CONSOLE(1)] "libggml-whisper
[chromium]    at Whisper.net.Logger.LogProvider.InitializeLogging(INativeWhisper nativeWhisper)
[chromium]    at Whisper.net.WhisperFactory.<>c.<.cctor>b__13_0()
[chromium]    at System.Lazy`1[[Whisper.net.LibraryLoader.LoadResult, Whisper.net, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
[chromium]    at System.Lazy`1[[Whisper.net.LibraryLoader.LoadResult, Whisper.net, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[chromium]    at System.Lazy`1[[Whisper.net.LibraryLoader.LoadResult, Whisper.net, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
[chromium]    at System.Lazy`1[[Whisper.net.LibraryLoader.LoadResult, Whisper.net, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null]].get_Value()
[chromium]    at Whisper.net.WhisperFactory.CheckLibraryLoaded()
[chromium]    at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
[chromium]    at Whisper.net.WhisperFactory.FromBuffer(Byte[] buffer, Boolean delayInitialization)
[chromium]    at SlideService.SlideService.LoadModel(String modelFilePath) in C:\workspace\Slide.net\SlideService\SlideService.cs:line 49
[chromium]    at SlideService.SlideService..ctor(String modelFilePath) in C:\workspace\Slide.net\SlideService\SlideService.cs:line 32
[chromium]    at SlideGuiMauiBlazor.Components.Pages.Slide.OnInitializedAsync() in C:\workspace\Slide.net\SlideGuiMauiBlazor\Components\Pages\Slide.razor:line 102
[chromium]    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[HWUI] Davey! duration=129668ms; Flags=0, FrameTimelineVsyncId=9685, IntendedVsync=147139655002, Vsync=276789649816, InputEventId=687100588, HandleInputStart=276801611200, AnimationStart=276801625100, PerformTraversalsStart=276803055800, DrawStart=276803178300, FrameDeadline=147172988334, FrameInterval=276800875900, FrameStartTime=16666666, SyncQueued=276803416800, SyncStart=276803489100, IssueDrawCommandsStart=276803581900, SwapBuffers=276807275200, FrameCompleted=276808085800, DequeueBufferDuration=13700, QueueBufferDuration=383300, GpuCompleted=276807940400, SwapBuffersCompleted=276808085800, DisplayPresentTime=0, CommandSubmissionCompleted=276807275200, 

Here is a screen shot of the dependencies in my project:
![SlideService  NET Dependencies](https://github.com/user-attachments/assets/b1ff7942-3c6e-4bb4-bf32-c795b8b90f4f)

Here is the .csproj file for my project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Add multiple frameworks for cross-platform support -->
    <TargetFrameworks>net8.0;net8.0-android;net8.0-ios</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>
    <!-- Required for MAUI Essentials -->
  </PropertyGroup>

  <ItemGroup>
    <!-- Add dependencies -->
    <PackageReference Include="NAudio" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Whisper.net" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Update="Whisper.net" Version="1.7.3" />
  </ItemGroup>
  
</Project>
```

**Comment by sandrohanea** [comment]
Hello @StevePGLS ,

Based on the `.csproj` listed above, it seems that you're missing the runtimes package. Please, add `Whisper.net.Runtime` package with the same version as `Whisper.net` to ensure that you'll have the native libraries in your Maui Blazor App.

**Comment by StevePGLS** [comment]
Thanks for the reply!!

So, I added in the Whisper.net.Runtime.  But it throws the same exception at the same place.  I have provided the log if that helps.  Your help is much appreciated.
[Slide_log_16Dec2024.log](https://github.com/user-attachments/files/18160664/Slide_log_16Dec2024.log)

**Comment by StevePGLS** [comment]
Will Whisper.net work when developing .NET MAUI targeting Android?  This issue logged here suggests that I may be doomed.

https://github.com/sandrohanea/whisper.net/issues/36#issuecomment-1537154189

**Comment by StevePGLS** [comment]
OK.  That worked!!!  Thank you so much Sandro!!

BUT... this worked because I'm using the Nuget packages for Whisper.net and Whisper.net.Runtime.  What I really need to do is modify Whisper.net.  In fact, I already have done that.  I had no problem doing this targeting Windows without Whisper.net.Runtime.  It would fail on Android.

So, now that I'm am modifying Whisper.net, I'm adding it as a project reference to SlideService.  What kind of reference should Whisper.net.Runtime be and from where?  Surely, I'm not using Nuget for that, right?

SlideGuiMauiBlazor: 
- SlideService.net (project reference)
- Whisper.net.Runtime (Where do I get this from?)

SlideService:
- Whisper.net (project reference)
- Whisper.net.Runtime (From where?)

Thanks!

**Comment by sandrohanea** [comment]
You can use the `Whisper.net.Runtime` from the package (nuget), they are not linked statically.

The only think that you need to be carefull will be when newer versions will appear to sync your fork of Whisper.net (project reference) if you want to upgrade `Whisper.net.Runtime` as it can grow with breaking changes (even between minor version bump) if Whisper.cpp will introudce new contracts. 

If you belive that some changes are required in `Whisper.net` you can also create some PR so you don't need to keep it as a fork that always require you to keep it up to date.

**Comment by sandrohanea** [comment]
> Is there are way I can know which version Whisper.net.Runtime that I should use based on when I did a "git clone" of Whisper.net? Like is there some version file in the project?

There is this file that shows the version that is currently in development: 
https://github.com/sandrohanea/whisper.net/blob/1c1ff13e5c47958de661005849432deb01bfa7e9/Whisper.net/Whisper.net.csproj#L7C5-L7C29

However, the best way to have a sync version is to always sync Whisper.net with a released tag (e.g. https://github.com/sandrohanea/whisper.net/tree/1.7.3)

This way you know that the tag represents the released version, and it is tested with the equivalent `Whisper.net.Runtime`

**Comment by sandrohanea** [comment]
Here you can find the tags and their commits for Whisper.net: https://github.com/sandrohanea/whisper.net/tags

**Comment by StevePGLS** [comment]
Do you know how to fix these errors?  A lot of them go away after manually deleting the \bin and \obj directories (clean doesn't always do it).  I still get this one:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\workspace\Slide.net\Whisper.net\bin\Debug\net8.0-android\android-x64\Whisper.net.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 126
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

**Comment by sandrohanea** [comment]
> Do you know how to fix these errors? A lot of them go away after manually deleting the \bin and \obj directories (clean doesn't always do it). I still get this one:
> 
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\workspace\Slide.net\Whisper.net\bin\Debug\net8.0-android\android-x64\Whisper.net.dll'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 126 at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
> 
> I'm using Whisper.net.Runtime version 1.7.1 because I cloned Whisper.net back in October.

Unfortunately, I don't know why you received that one but looks like some issue with the Maui build when referencing that project

**Comment by StevePGLS** [comment]
Sandro, again thank you so much for your help.  I am still having issues getting this to work with a compiled modified version of Whisper.net targeting Android on an emulator in Windows.  I have no problem getting this setup to work targeting Windows. 

Do your examples have one that is a .NET Maui project that works on Android?  I looked and didn't see one.

**Comment by StevePGLS** [comment]
As I understand it, the error I was getting [above](https://github.com/sandrohanea/whisper.net/issues/297#issuecomment-2555163767) to do with .NET Maui not correctly generating Whisper.net.dll for the correct architecture.  It gets the platform (Android) correct, but not the correct architecture (x86_x64).
