### ISSUE TITLE
System.Exception: 'Failed to load native whisper library.'

### ISSUE THREAD

**Issue by asadsafari** [sandrohanea/whisper.net#3]
HI, 

I have been trying to run this code, but I keep getting this error message:
**System.Exception: 'Failed to load native whisper library.'**

`
using System;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Forms;
using CommandLine;
using Whisper.net;
using Whisper.net.Ggml;
using Whisper.net.Wave;

namespace NameSpace
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {

            await Parser.Default.ParseArguments<object>(new string[] { })
                .WithParsedAsync(this.Demo);
        }
        string modelName = "ggml-base.bin";
        string filename = "1min.wav"; 
        async Task Demo(object opt)
        {
            if (!File.Exists(modelName))
            {
                Console.WriteLine($"Downloading Model ggml-base.bin");
                var modelStream = await WhisperGgmlDownloader.GetGgmlModelAsync(GgmlType.BaseEn);
                var fileWriter = File.OpenWrite(modelName);
                await modelStream.CopyToAsync(fileWriter);
            }

            FullDetection();
        }

     

        void FullDetection()
        {
            var processor = WhisperProcessorBuilder.Create()
            .WithSegmentEventHandler(OnNewSegment)
            .WithFileModel(modelName)
            .WithTranslate()
             .WithLanguage("auto")
            .Build();

            void OnNewSegment(object sender, OnSegmentEventArgs e)
            {
                Console.WriteLine($"CSSS {e.Start} ==> {e.End} : {e.Segment}");
            }

            var fileStream = File.OpenRead(filename);
            processor.Process(fileStream);
        }
    }
}

`

**Comment by sandrohanea** [comment]
Hello @asadsafari ,
Which OS are you using and which architecture?

Currently it is available for 
Windows Intel / AMD 64 bits
Linux Intel / AMD 64 bits
MacOS Intel 64 bits.

Support for ARM is still in progress (but should come soon).

**Comment by asadsafari** [comment]
Hey @sandrohanea 

I tested 2 machines: 
**First machine:** 
Windows 10, Intel(R) Core(TM) i5-2430M CPU , 32-bit operating system, x64-based processor

**Second Machine:**
Windows Server 2019, AMD, 64-bit operating system, x64-based processor

In addition, I have copied files like (whisper.dll,...)  to the bin folder of the project.

**Comment by sandrohanea** [comment]
Both should be supported already. `whisper.dll` should be automatically copied to "runtime/win-x64/whisper.dll".

Can you, please, check if the file is there?

In the meantime, for the next version, I'll throw a different exception if the library is not found or if it cannot be loaded.

**Comment by sandrohanea** [comment]
You can also try with version 1.2.1 where the loader is throwing different exceptions for library not found or library couldn't be loaded.

 https://www.nuget.org/packages/Whisper.net/1.2.1-preview1#versions-body-tab
 
 Usage changed a bit as well (now you need to create a WhisperFactory in order to get the builder). 
 The reason is that WhisperFactory can be shared across multiple threads and the model will be loaded only once.
 
 You can see updated usage here: https://github.com/sandrohanea/whisper.net/tree/release/1.2.1-pre#usage

**Comment by asadsafari** [comment]
It fixed, Really do not know how, 
Now I got a new error message:

The program '[6796] WinFormsApp2.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.
