### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies

### ISSUE THREAD

**Issue by ZhenyaPav** [sandrohanea/whisper.net#313]
**ChatGPT discussion**
 - [x] I asked [Whisper.net Helper](https://chat.openai.com/g/g-GQU8iEnAa-whisper-net-helper) and it couldn't help me, here is the discussion link: 

**Describe the bug**
When I use the package from nuget, I get this error:
```
E 0:00:20:0379   nint Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLoadError(): System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/libdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/liblibdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/libdl: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0/liblibdl: cannot open shared object file: No such file or directory

  <C++ Error>    System.DllNotFoundException
  <C++ Source>   :0 @ nint Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLoadError()
  <Stack Trace>  :0 @ nint Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLoadError()
                 :0 @ nint Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLoadError()
                 :0 @ string Whisper.net.LibraryLoader.LibdlLibraryLoader.GetLastError()
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
                 :0 @ Whisper.net.LibraryLoader.LoadResult Whisper.net.WhisperFactory+<>c.<.cctor>b__15_0()
                 :0 @ void System.Lazy`1.ViaFactory(System.Threading.LazyThreadSafetyMode)
                 :0 @ void System.Lazy`1.ExecutionAndPublication(System.LazyHelper, bool)
                 :0 @ T System.Lazy`1.CreateValue()
                 :0 @ void Whisper.net.WhisperFactory.CheckLibraryLoaded()
                 :0 @ Whisper.net.WhisperFactory..ctor(Whisper.net.Internals.ModelLoader.IWhisperProcessorModelLoader, bool)
                 :0 @ Whisper.net.WhisperFactory Whisper.net.WhisperFactory.FromPath(string, Whisper.net.WhisperFactoryOptions)
                 :0 @ Whisper.net.WhisperFactory Whisper.net.WhisperFactory.FromPath(string)
                 SpeechToText.cs:80 @ void SpeechToText.InitializeWhisper(string)
                 SpeechToText.cs:75 @ void SpeechToText+<SetConfig>d__11.MoveNext()
                 :0 @ void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                 :0 @ void System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(object)
                 GodotSynchronizationContext.cs:51 @ void Godot.GodotSynchronizationContext.ExecutePendingContinuations()
                 GodotTaskScheduler.cs:76 @ void Godot.GodotTaskScheduler.Activate()
                 ScriptManagerBridge.cs:84 @ void Godot.Bridge.ScriptManagerBridge.FrameCallback()
```

However, if I use whisper.net.dll I compiled myself (with _no_ changes), it works.
I think it could be due to some godot/dotnet shenanigans, as when I try to use something like this
```
    [DllImport("libdl")]
    public static extern IntPtr dlopen(string? filename, int flags);
```
From a godot script, it also throws an error, unless I change "libdl" to "libdl.so.2"

Changing "libdl" to "libdl.so.2" in the package's code might fix this, but I'm not sure as a self-built library works regardless.

**Comment by sandrohanea** [comment]
Hi @ZhenyaPav,
Can you please confirm which dotnet runtime are you using? Is it net framework with mono or dotnet core/ dotnet 8 / dotnet 9?

**Comment by ZhenyaPav** [comment]
> Hi @ZhenyaPav, Can you please confirm which dotnet runtime are you using? Is it net framework with mono or dotnet core/ dotnet 8 / dotnet 9?

Godot project uses dotnet 9, I built whisper.net library with dotnet 6 and 8

**Comment by sandrohanea** [comment]
> Godot project uses dotnet 9, I built whisper.net library with dotnet 6 and 8

With dotnet8 it shouldn't use that `LibdlLibraryLoader` but the `UniversalLbraryLoader`:  [here is the code](https://github.com/sandrohanea/whisper.net/blob/a3ec2f8fa8f19a5fd905dec2368aa16940dd35fd/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L61C33-L69C55)

Dotnet6 support was removed from Whisper.net for versions that were released after the [EOL of dotnet6](https://devblogs.microsoft.com/dotnet/dotnet-6-end-of-support/) 

 Maybe godot uses netstandard package for some reason and this is why it reaches that [LibdlLibraryLoader](https://github.com/sandrohanea/whisper.net/blob/1.7.4/Whisper.net/LibraryLoader/LibdlLibraryLoader.cs) instead of using the package for the dotnet 8 which uses the [UniversalLibraryLoader](https://github.com/sandrohanea/whisper.net/blob/1.7.4/Whisper.net/LibraryLoader/UniversalLibraryLoader.cs)
 
As a workaround, you can probably create a symlink for `libdl.so.2` named `libdl.so` on your target system, but some library fix is implemented in https://github.com/sandrohanea/whisper.net/pull/314 to load the native library from netstandard version on linux systems that only have `libdl.so.2`

**Comment by ZhenyaPav** [comment]
It seems like I made a mistake in my previous comment - the project was using dotnet 6 at that moment. With dotnet 9 version 1.7.4 indeed works without any errors.

**Comment by sandrohanea** [comment]
> It seems like I made a mistake in my previous comment - the project was using dotnet 6 at that moment. With dotnet 9 version 1.7.4 indeed works without any errors.

Glad it is working now. I also merged the fix that will allow libdl.so.2 to be used with the LibdlLibraryLoader in the future, so we'll close this issue for now. The fix will be released with the next Whisper.net version.
