### ISSUE TITLE
NuGet library is not able to load the whisper library on Android

### ISSUE THREAD

**Issue by guygodin** [sandrohanea/whisper.net#36]
The NativeLibraryLoader uses conditional preprocessor directives (#if ANDROID) which are not being applied so the existing NuGet ends up trying to load the Linux arm64 library and fails. Might be wrong but I think looking for the platform at runtime would be the correct way of supporting the various platforms. Cheers!

**Comment by drasticactions** [comment]
Can you create a reproduction project of what you're trying to do?

https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net.Runtime/Whisper.net.Runtime.targets#L68-L85

My guess is you're only referencing the project from a netstandard or net-6.0/net7.0 project, and not a native one. You would need to reference it in your native project (As in, reference Whisper.net and Whisper.net.Runtime in your Android project) for the right TFM to take effect.

**Comment by guygodin** [comment]
It is still producing the same exception when the Whisper.net and Whisper.net.Runtime packages are referenced in the native Android project. The exception thrown is:

`System.IO.FileNotFoundException: 'Native Library not found in path /data/data/com.companyname.whispertest/files/.__override__/runtimes/linux-arm64/whisper.so. Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.'`

I've attached a sample project that reproduces the issue
[WhisperTest.zip](https://github.com/sandrohanea/whisper.net/files/11412176/WhisperTest.zip)

**Comment by drasticactions** [comment]
@guygodin Ahhh, I see what you did.

This only supports net6+ projects; you're using Mono Android. That's why it defaults to the .NET Standard implementation since that's the baseline level for what you're targeting.

Update to the newest .NET Android (`dotnet workload install android` and `dotnet new android`) and it will work.

If you're hellbent on using Xamarin.Android instead, You should be able to do it. If you download the Whisper.net.Runtime nuget, extract the Android packages, link those to your project, and then set Bypass Loading to true (https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L25) it should work.

Although, again, I would upgrade to .NET Android.

**Comment by guygodin** [comment]
Ah got it, thanks for the insights. I'll look into bypass loading.

**Comment by guygodin** [comment]
Just FYI, the bypassLoading argument isn't being picked up because it is assigned after trying to load:

https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/WhisperFactory.cs#L36

**Comment by StevePGLS** [comment]
Hey there, is there still an issue with using .NET MAUI targeting Android?

Here is the issue I'm having:
https://github.com/sandrohanea/whisper.net/issues/297

**Comment by sandrohanea** [comment]
There should be no issue in general with the .NET MAUI with Whisper.net targeting Android as we have tests for this scenario which are currently passing: https://github.com/sandrohanea/whisper.net/actions/runs/12241499842/job/34147156501

The native runtime should be referenced with `Whisper.net.Runtime` package which is using `AndroidNativeLibrary` :
https://github.com/sandrohanea/whisper.net/blob/2356c59d934f901cc6f20ccd025526b49ac59b74/runtimes/Whisper.net.Runtime/Whisper.net.Runtime.targets#L116C3-L116C24

We only support the following Abis: `x86`, `x86_64`, `arm64-v8a`

The manual loading is bypassed now: https://github.com/sandrohanea/whisper.net/blob/2356c59d934f901cc6f20ccd025526b49ac59b74/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L23C9-L23C66
