### ISSUE TITLE
netstandard2.0 dll is not installed

### ISSUE THREAD

**Issue by rakib33** [sandrohanea/whisper.net#38]
I will run this project in visual studio 2022 ,all dll is installed but netstandard2.0 is not installed . I installed .Net Core 2 and Desktop Development C++ library but still this error remain.
![netstandard2 0](https://user-images.githubusercontent.com/10026710/237007911-68309101-26a7-4929-acb5-483915f542c3.PNG)

**Comment by drasticactions** [comment]
Because you need to install .net 6 or above and those workloads.

Install .NET 6 or above, and run `dotnet workload install macos ios maccatalyst android`

**Comment by sandrohanea** [comment]
Hello @rakib33 ,
Did you manage to run the demo with the instructions provided by @drasticactions ?

**Comment by rakib33** [comment]
Dear @sandrohanea  ,
Still not working .After install some library .Net Framework 4 to 4.6 or visual studio 17 .NetSatndard 2 issue is resolved but some others library not found after run dotnet workload install macos ios maccatalyst android command . Now I create a fresh project in VS 2019 install nuget package Whisper.Net . Now can't understand your program.cs code from Whisper.net.Demo project. I need to do speech to text using tiny model .Would you please share me some sample.

**Comment by drasticactions** [comment]
Okay, that's your issue: You can't compile this in VS 2019, you need VS 2022.

VS 2019, as far as I'm aware, has limited compatibility with dotnet 5+ projects, and most likely it can't compile with these workloads. You need VS 2022 to compile the solution in Visual Studio.

That said, as you saw, you can still reference and use this project in .NET Framework. If you take the example code and put it into a .net framework console project, it should load.

IMO, I would upgrade to VS 2022 though.

**Comment by sandrohanea** [comment]
Maybe it will be good to add some simpler examples in a new SLN for easier understanding of the usage.

**Comment by sandrohanea** [comment]
Added https://github.com/sandrohanea/whisper.net/tree/main/examples/SimpleWhisperExample
