### ISSUE TITLE
how to retrieve diarization and how to use prompt?

### ISSUE THREAD

**Issue by acidmeat** [sandrohanea/whisper.net#40]
there is no interface in the binding?

**Comment by sandrohanea** [comment]
Hello @acidmeat ,

Prompt for the Whisper model you can provide using the extension method: [WithPrompt](https://github.com/sandrohanea/whisper.net/blob/d31d84bb1503e6a23123988f4b6e433296ffa79e/Whisper.net/WhisperProcessorBuilder.cs#LL286C5-L286C61)

However, that is not used with any LLM (as some of the examples in whisper.cpp) but it's just the prompt used as the input for the transcribing / translation.

Regarding diarization, this is not in the library, but in the client implementation (main) in whisper.cpp:

https://github.com/ggerganov/whisper.cpp/blob/95b02d76b04d18e4ce37ed8353a1f0797f1717ea/examples/main/main.cpp#L237

I can implement some examples where diarization is used simillar to that "main" example. Will keep you posted.

**Comment by sandrohanea** [comment]
Hello @acidmeat ,
Diarization example is here: https://github.com/sandrohanea/whisper.net/blob/main/examples/DiarizationWhisperExample/Program.cs
