### ISSUE TITLE
Where should I insert my api key?

### ISSUE THREAD

**Issue by ShlomiShif** [sandrohanea/whisper.net#42]
I implemeted this library per the example provided here and I get the following exception when trting to submit requests:
System.Security.Authentication.AuthenticationException: Authentication failed

I guess this is due to missing api key.

**Comment by sandrohanea** [comment]
Hello @ShlomiShif ,
The issue you are facing is most likely caused by another part of your application.

Whisper.net is based on Whisper.cpp and runs locally so it doesn't need any api key nor other form of authentication in order to run the model.

**Comment by sandrohanea** [comment]
Will close this for now as it doesn't seem related to the Whisper.net library.

**Comment by theolivenbaum** [comment]
Was probably due to an old download URL from huggingsface - I saw the same issue before when debugging why the downloader stopped working.
