### ISSUE TITLE
Win-x64 library issue

### ISSUE THREAD

**Issue by robinlacey** [sandrohanea/whisper.net#44]
Hello

In both 1.4 (and the newly released 1.4.2) I'm getting the error 
```System.Exception : Failed to load native whisper library. Error: The specified module could not be found.``` 

I've dug into the Whisper.net.Runtime package and it looks like the `win-x64/whisper.dll` is not supported. The Rider assembly explorer is flagging it as a `Win32 resource` - perhaps the pipeline built the wrong file? 

Suggestions on how to fix?

Many thanks

**Comment by sandrohanea** [comment]
Hello @robinlacey ,
That's strange as I'm using win64 as well and it is working.

1.4.2 was built these libraries with Visual Studio Community 2022.

I suspect you're missing some dependency of the native library (e.g. MSVC Redistributable) https://aka.ms/vs/17/release/vc_redist.x64.exe

Can you, please, try to re-install the above and write an update if you still have the issue?

**Comment by robinlacey** [comment]
That did it 🎉 Thanks for the quick response!
