### ISSUE TITLE
Only 16KHz sample rate is supported.

### ISSUE THREAD

**Issue by LoserFeng** [sandrohanea/whisper.net#55]
Whisper.net.Wave.NotSupportedWaveException
  HResult=0x80131500
  Message=Only 16KHz sample rate is supported.

How To solve this problem

**Comment by sandrohanea** [comment]
Hello @LoserFeng ,
Currently in order to convert any wave file to the supported wave format, I recommend using either NAudio or FFmpeg (depending what type is your input file). We don't want to add this as a dependency to the base package, but some example will be added for this.

**Comment by sandrohanea** [comment]
Added example on how to use NAudio (another open-source library) to resample a wave file: https://github.com/sandrohanea/whisper.net/blob/main/examples/NAudioResampleWav/Program.cs
