### ISSUE TITLE
The program has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.

### ISSUE THREAD

**Issue by asadsafari** [sandrohanea/whisper.net#7]
Hi, 
I got this error message, which indicates that a program has attempted to execute an invalid or unsupported CPU instruction. My CPU is Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz , X64-based processor. 

Any idea? 

The code 

`void FullDetection()
        {
            var processor = WhisperProcessorBuilder.Create()
            .WithSegmentEventHandler(OnNewSegment)
            .WithFileModel(modelName)
            .WithTranslate()
             .WithLanguage("auto")
            .Build();

            void OnNewSegment(object sender, OnSegmentEventArgs e)
            {
                textBox1.Text= ($"CSSS {e.Start} ==> {e.End} : {e.Segment}");
            }

            lock (new object())
            {
                using (var fileStream = File.OpenRead(filename))
                {
                    processor.Process(fileStream);
                }
            }

        }`

**Comment by sandrohanea** [comment]
Can you maybe try to download the official https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.0 to see if you have any issue with the native implementation?

**Comment by 7702244** [comment]
I have the same issue on Windows Server 2019 x64. Tried all whisper.cpp versions from 1.2.0 to 1.3.0. Do you find any workaround?
On Mac OS with Apple Silicon everything works perfectly.

**Comment by sandrohanea** [comment]
I couldn't manage to reproduce this error :(
Can someone try to reproduce it (preferably on latest version, 1.3.0) and provide me some repo where I can test it?

Thank you!

**Comment by sandrohanea** [comment]
Will close this for now as we don't have any activity for quite some time, if someone manages to reproduce it with newer version, don't hesitate to open a new issue.
