### ISSUE TITLE
Issue with Wave Memorystream obtained through ffmpegcore

### ISSUE THREAD

**Issue by Kanda** [sandrohanea/whisper.net#74]
I seem to have run into an issue with a memorystream created by letting ffmpegcore download a video and stripping the audio from it.
As soon as it arrives at the ProcessAsync call. The application uses almost 10 gigs of memory. Calling Process instead of the async variant leads to "unable to read beyond the end of the stream"

I debugged part of it already and saw that the dataChunkSize seems to be massive compared to the memorystreams length (memory streams length: 888910)(https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/Wave/WaveParser.cs#L356)
When I hardcoded the dataChunkSize to be the length, it read the stream fine and gave me the expected output.

I wondered if you could tell me what might be the issue here. Either by the settings for the wave (unsupported codec or something else) or what might go wrong with reading the created memorystream. I added an example project to this post. (You might need to get the required ffmpeg binaries from [https://ffbinaries.com/downloads](https://ffbinaries.com/downloads))

[WhisperIssueExample project](https://github.com/sandrohanea/whisper.net/files/11751055/WhisperIssueExample.zip)

**Comment by Kanda** [comment]
Hello @sandrohanea,

Thank you for addressing this issue with such promptness. I came across the updated nuget package that supposedly includes the fix as per the changelogs. However, upon using the package, I encountered the same issue where it still consumed 10gigs of memory. On the other hand, when I referenced the repository and debugged the code, it ran smoothly without any issues.

I have tried to identify the root cause of this anomaly but to no avail.

**Comment by sandrohanea** [comment]
Hello @Kanda ,
Just to confirm:
1. You installed `Whisper.net` 1.4.4 and `Whisper.net.Runtime` 1.4.4 ?
2. Have you tried to clean/rebuild after the upgrade?

**Comment by Kanda** [comment]
Hello @sandrohanea,

I have indeed updated both of them to 1.4.4 and have done both a clean/rebuild and a full delete of the bin and obj folder. To make sure to force a clean build.

I do know it has the new version cause the downloader now includes the QuantizationType. So I aint certain at this point why it isn't working with the nuget package.

**Comment by sandrohanea** [comment]
Sorry for the confusion, I decompiled the Whisper.net 1.4.4. and indeed it's not containing the fix:
![image](https://github.com/sandrohanea/whisper.net/assets/40202887/9d6ea3d0-f926-4559-a3b1-0928a90b4ed5)

I don't know how I did that, but for some reason, the fix is not included in the build, but other fixes (even after that one, are present):
![image](https://github.com/sandrohanea/whisper.net/assets/40202887/5ed52aea-7559-495f-8bbf-0ea6967befbb)

**Comment by Kanda** [comment]
There is no rush for my project currently so take your time

**Comment by sandrohanea** [comment]
Release 1.4.5 now, tested specifically this fix and it's working as expected using the nuget version.
