### ISSUE TITLE
Controlling the length of the generated text segments

### ISSUE THREAD

**Issue by HillCat** [sandrohanea/whisper.net#82]
Please ignore this post.

**Comment by HillCat** [comment]
![image](https://github.com/sandrohanea/whisper.net/assets/41800196/cb641c3e-5cb6-40d5-9437-f5496b1a0ea9)

**Comment by sandrohanea** [comment]
In case someone else needs this and will find this issue by searching, you can archive this (controlling the length of the generated text segments) using:
```
        .WithTokenTimestamps()
        .WithMaxSegmentLength(15)
```
