### ISSUE TITLE
Identifying two speakers

### ISSUE THREAD

**Issue by yakovw** [sandrohanea/whisper.net#87]
Is there any built-in way to identify two speakers?
Thank you

**Comment by sandrohanea** [comment]
Currently, the only option to identify different speakers is if each speaker will be recorded in a different channel, and in this case, diarization can be used as in example: https://github.com/sandrohanea/whisper.net/blob/main/examples/Diarization/Program.cs

However, if the speakers are not isolated in different channels, there is this on-going effort in the nartive library: https://github.com/ggerganov/whisper.cpp/pull/1058

If that will work and will be merged, this dotnet binding will probably add support as well.

**Comment by yakovw** [comment]
Thank you

**Comment by fitdev** [comment]
Seems like it has been merged to Whisper.cpp last year. Any plans on adding support for this?

**Comment by sandrohanea** [comment]
Hello @fitdev ,
Indeed, it seems that it was merged. Will need to be reviewed and integrated for easier use in dotnet, but probably those models are already usable (didn't tested them myself yet).
