### ISSUE TITLE
Faster transcription

### ISSUE THREAD

**Issue by yakovw** [sandrohanea/whisper.net#89]
I tried using WithThreads
I have a very powerful processor
But it didn't help anything, although it took more power from the processor, but it took the same amount of time, which means I just lost
Is there something I'm doing wrong?
I tried too
WithSpeedUp2x
And then it just doesn't transcribe anything!
Thanks for this wonderful library
and for your help

**Comment by sandrohanea** [comment]
For faster transcription, you can use different runtime versions (e.g. Whisper.net.Runtime.Cublas for nvidia GPU) 

Not all the computations are offloaded to GPU even if Cublas is used: see more info in https://github.com/ggerganov/whisper.cpp/tree/master

This library is a wrapper around whisper.cpp, so it cannot run faster than that. 

If you have some option where https://github.com/ggerganov/whisper.cpp/tree/master is running considerably faster than whisper.net => it might be an issue in this wrapper (e.g. in parsing the wave file). but nothing like that was reported yet.
