### ISSUE TITLE
Tiny CoreML zip file contains duplicate of itself

### ISSUE THREAD

**Issue by philippjbauer** [sandrohanea/whisper.net#93]
All files in the CoreML encoder directory exist as a duplicate within themselves:

<img width="292" alt="Screenshot 2023-07-03 at 10 07 15 AM" src="https://github.com/sandrohanea/whisper.net/assets/3707196/ca59f2d0-0400-4a0a-bacf-f6cd075a4b56">

**Comment by sandrohanea** [comment]
Thanks @philippjbauer for reporting,
Finally got to it and fixed it in: https://huggingface.co/sandrohanea/whisper.net/commit/52d442449e62c86ec74a8b4711c23ec6c0fb30c1

Also fixed the large encoder which contained both the large and large-v1, now they are 2 different zips :)
