### ISSUE TITLE
WithNoSpeechThreshold doesn't seem to do anything

### ISSUE THREAD

**Issue by AWAS666** [sandrohanea/whisper.net#96]
Either I lack the understanding what this is supposed to do or it doesn't work.
I tried a variety values from 0.1f to 10f and I still had hallucinations remaining in my output, so stuff like "you" repeatedly which seems to occur whenever an empty audio stream is passed to whisper as that has likely not been including in the model training data.

**Comment by sandrohanea** [comment]
Hello @AWAS666 ,
Indeed, the no speech Threshold is not supported yet in the underlying library :

https://github.com/ggerganov/whisper.cpp/blob/7b374c9ac9b9861bb737eec060e4dfa29d229259/whisper.h#L406

Once it will be implemented there, whisper.net should automatically support it but as a workaround until that will be added, recommend you to use `WithProbabilities`: https://github.com/sandrohanea/whisper.net/blob/2c13353b13e0a6d8ef38e5aa3cc77c7da77661eb/Whisper.net/WhisperProcessorBuilder.cs#L494

And check for confidence level on each segment with `Probability` property: https://github.com/sandrohanea/whisper.net/blob/2c13353b13e0a6d8ef38e5aa3cc77c7da77661eb/Whisper.net/WhisperProcessorEvents.cs#L25C9-L25C20

Please note that it will be probably changed to `WithConfidence` and `ConfidenceLevel` in the upcoming versions.

**Comment by sandrohanea** [comment]
Good news, @AWAS666 !

`WithNoSpeechThreshold`  was implemented in the underlying library and will be released with the version 1.7.4 of Whisper.net soon. (already merged to master)

**Comment by andreaLeo** [comment]
Hello @sandrohanea  ;

thanks for all the work you've done here ! 
i tried to use WithNoSpeechThreshold property but then as 1.7.3 but it seems to not detect silence on my audio

**Comment by sandrohanea** [comment]
Hey @andreaLeo ,

The implementation was released only on 1.7.4 version for `Whisper.net` (not 1.7.3).

**Comment by andreaLeo** [comment]
sorry just read again my message, i miss written.
my segments are including silence

**Comment by andreaLeo** [comment]
do someone have the same issue as me ? WithNoSpeechThreshold  is not zorking on 1.7.4 for me :(

**Comment by andreaLeo** [comment]
maybe i set a wrong value, i set -30.0f

**Comment by sandrohanea** [comment]
Indeed, I think this value is wrong.

Default value in the state is 0 =>     [float no_speech_prob = 0.0f;](https://github.com/ggerganov/whisper.cpp/blob/f28bf5d1864fe039060a9fa84ffe72433d20153e/src/whisper.cpp#L949C5-L949C33)

This should be a probability (I believe between 0f and 1f).

Newer versions of whisper.net (currently only 1.7.5-preview1) also have NoSpeechProbability which provides the actual value for each segment (you can use it to see which is a good threshold for you).

![Image](https://github.com/user-attachments/assets/68df7246-7c2c-47be-8301-ba2cc509ea56)
